### DISCUSSION TITLE
Is it possible to override dark mode in `presetWindi`?

### DISCUSSION THREAD

**Discussion by dungsil** [unocss/unocss#1059] [Q&A] [answered]
hello. I have a question while using presetWindi, so I leave a question.

Is it possible to change the `class="dark"` it creates from the `dark:` prefix to `data-color-schema="dark"` etc.?

**Comment by chu121su12** [comment, marked as answer]
Could you elaborate more, probably with example?

**Reply by dungsil** [reply]
I solved it by doing the following

thanks 🥲

```js
presetWindi({
 dark: 'media'
})
```

```css
[data-color-schema="dark"] {
  prefers-color-scheme: dark;
}
```
