### DISCUSSION TITLE
Can we please get arbitrary variants

### DISCUSSION THREAD

**Discussion by louiss0** [unocss/unocss#1481] [Ideas]
# Introduction

I want to have a feature that allows me to put `class="[=variant name=]:(bg-gray-500)"`  and it would turn into a pseudo class or pseudo element. Since no one can come up with all of the possible variants that someone can use why not allow for them to be compiled on the fly. That way no one has to configure them at all it just compiles.  

The syntax looks like this. 

```html 

<progress class="[::-webkit-progress-value]:(bg-red-500 text-gray-700) [::-webkit-progress-bar]:(bg-red-700 text-gray-900)"> </progress>

```

```css

::-webkit-progress-value {
  background: red
color: gray
}

::-webkit-progress-bar{
  background: red
color: gray
}
}
```
tailwind css has this feature you should check it out  [tailwind arbitrary variants](https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants)
