### DISCUSSION TITLE
Exclude comments from analysis

### DISCUSSION THREAD

**Discussion by manvankaliber** [unocss/unocss#1575] [Q&A]
This html...
```html
<!-- lowercase -->
<div class="text-red-500"></div>
```
... generates the following css...

```css
/* layer: default */
.lowercase{text-transform:lowercase;}
.text-red-500{--un-text-opacity:1;color:rgba(239,68,68,var(--un-text-opacity));}
```
.. when using the default playground config.

How can I exclude the comments from being analyzed so the `lowercase` utility in this example will not be generated?
