### DISCUSSION TITLE
: hover::before how to convert with unocss

### DISCUSSION THREAD

**Discussion by bd-dxg** [unocss/unocss#1680] [Q&A] [answered]
我有一些 css 样式是基于 :hover::before 的, 该如何使用 unocss 做转换呢?(I have some css styles based on: hover::before, how can I use unocss to do the transformation?)
```css
ul li:hover::before {
  transform: scale(0.9);
  background-color: #bfa;
  border-radius: 50%;
}
```
我希望能够使用 windi 变体来写  例如:(I want to be able to use windi variants to write things such as:)

```html
<ul class="grid grid-flow-col gap-16px">
      <li class="li-style" hover:before="scale-90 bg-#bfa rounded-1/2">
       1111111111111
      </li>
</ul>
```
或者(or)
```html
<ul class="grid grid-flow-col gap-16px">
      <li class="li-style" before:hover="scale-90 bg-#bfa rounded-1/2">
       1111111111111
      </li>
</ul>
```
但他们都没有生效,没有效果(But none of them worked. They didn't work.)

请大家帮帮我,非常感谢!(Please help me, thank you very much!)
