### DISCUSSION TITLE
Preflights generated multiple times

### DISCUSSION THREAD

**Discussion by fehnomenal** [unocss/unocss#2109] [Ideas]
Please forgive my ignorance, but why do we generate the same css for each of the preflight roots and join than instead of joining them and generate the css once?

https://github.com/unocss/unocss/blob/7ce275695725c82dc012f4c4f0c2702645c5a1d0/packages/preset-mini/src/preflights.ts#L11-L12

There shouldn't be any difference between
```css
.a{color:red}.b{color:red}
```
and
```css
.a,.b{color:red}
```
right?
