### DISCUSSION TITLE
Is there a way to make scss file and unocss.config share the same color variable?

### DISCUSSION THREAD

**Discussion by lainbo** [unocss/unocss#2143] [Q&A]
```scss
// .scss
$primary: #5b61ff;

@function hexToRGB($hex) {
  @return red($hex), green($hex), blue($hex);
}

:root {
  --primary-rgb-color: #{hexToRGB($primary)};
}
```

```ts
// unocss.config.ts
// ...
export default defineConfig({
  theme: {
    colors: {
      primary: #5b61ff,
    },
  }
})
```

I made the declarations `#5b61ff` twice, is there any way to merge them, let `#5b61ff` be declared only once.
