### DISCUSSION TITLE
Arbitrary values with strings

### DISCUSSION THREAD

**Discussion by ws-rush** [unocss/unocss#2222] [Q&A] [answered]
How I can pass strings to Arbitrary values like content-['hell'] which not acceptable,

does unocss support syntax prop-['value'] at all?

**Comment by SnowingFox** [comment]
can u provide a example?

**Reply by ws-rush** [reply]
`after:content-['*']`

**Reply by SnowingFox** [reply]
> `after:content-['*']`

you should not write value with `'`, just write like `after:content-[hello_world]`

`output css`
```css
/* layer: default */
.after\:content-\[hello_world\]::after{content:hello world;}
```

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIEDMAuBTAJwC4YB7AO30oFoBtACzzjlIH0B3UguEAXXSgB6AHxA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVHQAFtAwEjx0AFyIVKh6YXQwOgC0QSFhMHpRejBWMElOpHA5lnnQ9rikGHDBAG4YUBHFeTn2TmaoarIiCpFwANoxcqJKKj4AlLLC8owsbJw8fPzjk0MKktJ%2BgwESrRhRAIwAdABMK6gSaLhZgaxgkQD09-Qgh0H37ahwahNUALpI3yQQA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Reply by ws-rush** [reply]
that is the point, if there is no '' or "" around generated CSS, it will not show,

if you tried in CSS:

```css
.content::before {
    /* this work */
    content: 'hello';
    /* but this no */
    content: hello;
}
```
