### DISCUSSION TITLE
[Nuxt3] Styles from @apply directives are missing in production bundle when cssnano is active

### DISCUSSION THREAD

**Discussion by meixger** [unocss/unocss#2227] [General]
(from https://github.com/nuxt/nuxt/issues/19177)

I'm trying to get UnoCSS + Nuxt 3 + [daisyUI](https://github.com/saadeghi/daisyui) to work together.

Styles from `@apply` directives are working fine in the Nuxt development server.
But in the production bundle some styles are missing depending on the order.
Disabling cssnano in nuxt.config.ts resolves the error.

```css

.text1 {
  @apply bg-slate-200;
  @apply text-center;
}
.test2 {
  @apply text-center;
  @apply bg-slate-200;
}
```

```css
/* bundle output */
.test1{--un-bg-opacity:1;background-color:rgba(226,232,240,var(--un-bg-opacity));text-align:center}
.test2{--un-bg-opacity:1;background-color:rgba(226,232,240,var(--un-bg-opacity))} /* <-- MISSING text-align:center */
```
---
Reproduction:
---

https://stackblitz.com/edit/github-gxjzue?file=nuxt.config.ts

Note: Error happens only on Nuxt production build with cssnano enabled
