### DISCUSSION TITLE
RGB-css variables not rendering properly

### DISCUSSION THREAD

**Discussion by itzaks** [unocss/unocss#2350] [Q&A]
I'm trying to get rgb css-variables to render properly with hover variants affecting the opacity.

It works just fine [on this playground](https://unocss.antfu.me/play/?html=DwEwlgbgfAUABHUk4CMDmBeARAEgA4BOYAtgIYECeAtAWinABYD2EApgQFxN6kDGYAF2oBWAAxYoASQDkxOADNSIViDhMAdoxbtgAenDQYeg7CA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQoSLDhcAhlirpoIVFABqe7gZgBxaXzCTpsuQAFFEFVQD0%2Bw8ZQplAAtABuVsA2IUQOYBrqqAAe2vBo6Hp8ADZpGNh4BMQAFAjqcOSUNDBUAFxwANosVQwQRQCUzJXsnNz8giLtALokZbpQBkYmZrUN-pNBZpbWWHZxQyPlVAAW0DBKAjP1o%2BVH5WdwPgB6RQB0ANRtIQA6ACS3dwD8IVBEPG0vPg25zgRXqZD4ZCUgzacAAvAA%2BOAAAxeCD4YhC9R%2BPCKESgRRCIVRSjEHTxBJCiiJaIxEDAeiUwBgwhIAEY2m1BkigeVhqM%2BaT1EA&css=FwJw9mAuDeBQAE8C0SAOICWBbAhiAnkiAOYBGw8ADADTwCMATABy0MCsbA3LAL5A&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA).

_Output:_
````css
/* layer: shortcuts */
[bg~="\$primary-rgb"]{background-color:rgb(var(--primary-rgb),var(--un-bg-opacity,1));}
/* layer: default */
[bg~="hover\:opacity-50"]:hover{--un-bg-opacity:0.5;}
.hover\:opacity-50:hover{opacity:0.5;}
/* layer: playground */
:root{
  --primary-rgb: 0, 128, 255;
}
````

However when I try to render the same code in my app, with the same unocss-config as in the playground, my result is different. It's using `@unocss/nuxt` though. Same version, transformers and plugins.

My input looks like this:
````vue
<template><div bg="$primary-rgb hover:opacity-50"></div></template>

<script lang="ts" setup>
</script>
`````

But the output is like this
````css
/* layer: default */
[bg~='\$primary-rgb'] {
  background-color: var(--primary-rgb); /* just 255, 102, 71 */
}
[bg~='hover\:opacity-50']:hover {
  --un-bg-opacity: 0.5;
}
````

This exists in the root and resolves in the browser. 
````css
:root {
    --test-rgb: 255, 102, 71;
}
````

Am I missing some layering issue here, or anyone has an idea on what could be the problem?
