### DISCUSSION TITLE
Usage help. How to group few selectors?

### DISCUSSION THREAD

**Discussion by lvjiaxuan** [unocss/unocss#2498] [Q&A] [answered]
My normal CSS like this:
```css
input[type=number], input[type=text] {
  color: red
}
```

I can only:
```html
<div class="[&[type=number]]:c-red [&[type=text]]:c-red" />
```

Is there a better available utilities to style it?
