### DISCUSSION TITLE
Customize markup using runtime only

### DISCUSSION THREAD

**Discussion by jbrodriguez** [unocss/unocss#2534] [Q&A]
this is a hugo setup, what i want to do is use unocss as runtime only, so i have

`index.html`
```html
<head>
{{- $css := resources.Match "css/*.css" | resources.Concat "css/main.css" -}}
{{- if hugo.IsProduction }} {{ $css = $css | minify | fingerprint }} {{end -}}
<link 
  rel="stylesheet" 
  href="{{ $css.RelPermalink }}" 
  {{ if hugo.IsProduction }}  integrity="{{ $css.Data.Integrity }}" {{ end }}
/>
<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime"></script>
</head>
```

`main.css`
```css
:root { font-family: 'Inter', system-ui,-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif; }
@supports (font-variation-settings: normal) {
  :root { font-family: 'Inter var', system-ui,-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif; }
}

html {
  @apply text-xl leading-6
}

h1 {
  @apply text-gray-400 text-3xl font-bold mt-10 mb-2
}
```
the issue i have is that the per-element styles are not getting applied

can anyone provide some help on this ?
