### DISCUSSION TITLE
How to set custom icons

### DISCUSSION THREAD

**Discussion by wuchaoxin** [unocss/unocss#2665] [Q&A] [answered]
I have a somewhat confused question, when I want to set up custom icons myself, I find it very difficult in grammar. I must set up images in SVG format in collections/custom. Can I use other formats or can I scan according to a certain directory?

我有一个比较疑惑的问题，在我想要自己设置自定义图标时，我发现这在语法上十分困难。我必须在 collections/custom 设置 svg 格式的图片，我是否能使用其他格式或者我是否能够按照某个目录去扫描？

**Comment by wuchaoxin** [comment]
Another question, how can I use unocss syntax to set background images?

还有一个疑问，我如何用 unocss 语法去设置背景图片呢？

**Reply by MellowCo** [reply]
try it 

1. net image

```html
<div class="bg-[url(https://xxxxxxxxxxx)]">
```

2. public dir

use `/public` accessing images under public dir

```html
<div class="bg-[url(/public/favicon.svg)]" />
```

automatically convert after packaging
```css
.bg-[url(/public/favicon.svg)] {
    --un-url: url(/assets/favicon-cc59bced.svg);
    background-image: var(--un-url)
}
```
