### DISCUSSION TITLE
配置文件中的规则Rules怎么应用媒体查询media的规则

### DISCUSSION THREAD

**Discussion by wtto00** [unocss/unocss#2696] [Q&A] [answered]
我在配置文件中写了个规则
```ts
rules: [
  [/^grid-columns-(\d+)$/, ([, d]) => ({ 'grid-template-columns': `repeat(auto-fill, ${Number(d) / 4}rem)` })],
]
```

然后我使用 `grid-columns-40` 是能正确编译到：
```css
.grid-columns-40 {
    grid-template-columns: repeat(auto-fill, 10rem);
}
```
但是当我使用 `md:grid-columns-44` 时，却没有什么编译输出：
```css
/* nothing */
```
我想要正确的输出：
```css
@media (min-width: 768px) {
  .md\:grid-columns-44 {
    grid-template-columns: repeat(auto-fill, 11rem)
  }
}
```
