### DISCUSSION TITLE
How to use  CSS feature query

### DISCUSSION THREAD

**Discussion by wuchaoxin** [unocss/unocss#2799] [Q&A] [answered]
In Sass, we can write the following code by mixing in to use CSS feature queries. I am curious about how to use it in unocss?
在 sass 中，我们可以通过混入写出以下代码，去使用 CSS 特性查询，我很好奇如何在 unocss 中使用？

```scss
@mixin autoFontWeight($number) {
  font-weight: $number;
  @supports not (-webkit-touch-callout: none) {
    // 非 ios 设备
    @if ($number > 400) {
      font-weight: bold;
    } @else {
      font-weight: normal;
    }
  }
}
```

**Comment by wuchaoxin** [comment]
Can I use CSS feature queries in rules or shortcuts?
我是否可以在 rules 或者 shortcuts 中使用 CSS 特征查询？

**Comment by m4rrc0** [comment]
Also interested!
And very surprised there is no discussion about this.

My personal use case is:
```css
.lg\:sideways-lr { writing-mode: sideways-lr; }

@supports (not (writing-mode: sideways-lr)) {
	.lg\:sideways-lr {
		writing-mode: vertical-rl;
		transform: rotate(-180deg);
	}
}
```

If you don't need variants, you can do a [Fully Controlled Rule](https://unocss.dev/config/rules#fully-controlled-rules)... something like this:

```js
// uno.config.ts
import { defineConfig, toEscapedSelector as e } from 'unocss'

export default defineConfig({
  rules: [
    [/^sideways-lr$/, ([, name], { rawSelector, currentSelector, variantHandlers, theme }) => {
      // if you want, you can disable the variants for this rule
      if (variantHandlers.length) {
        // NOTE: there may be a way to process variants manually here but I cannot find any documentation
      }

      const selector = e(rawSelector)

      return `
${selector} { writing-mode: sideways-lr; }

@supports (not (writing-mode: sideways-lr)) {
	${selector} {
		writing-mode: vertical-rl;
		transform: rotate(-180deg);
	}
}
`
    }],
  ],
})
```
It works but since variants are not applied, there is little to no benefit in writing a rule for this. One might as well write classic CSS.

As noted in the comments, there might be a way to process variants manually with `variantHandlers` but it is not straightforward and I don't think there is a canonical (read 'copy-paste') way of processing all variants with their normal behaviors.
I hope I am wrong and someone can correct me.

Good luck.
