### DISCUSSION TITLE
Is it possible to store a UnoCSS shortcut inside a CSS variable and then load this CSS variable inside a different shortcut?

### DISCUSSION THREAD

**Discussion by bennymi** [unocss/unocss#2899] [Q&A] [answered]
Something like this:

```css
:root {
  --text-size: "text-2xl";
}
```
```javascript
shortcuts: [
  ['text-size', 'var(--text-size)']
]
```
