### DISCUSSION TITLE
CSS generation based on multiple element attributes

### DISCUSSION THREAD

**Discussion by aarongeorge** [unocss/unocss#2937] [Q&A]
Say I have the following html

```html
<div data-layout='center' data-gutters>Some text</div>
```

I want to generate the following output:

```css
:root {
	--center-gutter-width: 10px;
	--center-max-width: 90ch;
}

[data-layout=center] {
	display: block;
	box-sizing: content-box;
	margin-inline: auto;
	max-inline-size: var(--center-max-width);
}

[data-layout=center][data-gutters] {
	padding-inline-start: var(--center-gutter-width);
	padding-inline-end: var(--center-gutter-width);
}
```

The thing is I only want the last selector `[data-layout=center][data-gutters]` generated if the element contains both attributes.

What is the best approach to do this? So far I haven't been able to get all attributes per element into the rules generation function.

I built an extractor just for `data-` attributes but it seems to want a flat array of strings returned (leaving me without a way to get all the attributes for an element in the matcher.

Any help would be greatly appreciated, thank you!
