### DISCUSSION TITLE
Why do shortcuts @apply classes instead of reusing the existing atomic css?

### DISCUSSION THREAD

**Discussion by wmertens** [unocss/unocss#2955] [General]
I'm wondering, if you have a shortcut `foo: "w-3 h-3"`, then it will output basically `.foo { @apply w-3 h-3; }`.

Can't it instead output `.foo, w-3 { ... }; .foo, h-3 { ... };`?

Then you're reusing the atomic CSS instead of creating copies.

**Comment by wmertens** [comment]
still wondering, hoping that someone can tell me if this is a bad idea or not?

**Comment by zyyv** [comment]
Why do you want to do this? The shortcut is to assemble commonly used utilities together instead of flattening them.

**Reply by wmertens** [reply]
because it's no longer atomic CSS, so it feels "wrong" :)

e.g.
```css
.w-6 { width: 1.5rem; }
.h-6 { height: 1.5rem; }
.s-6 { width: 1.5rem; height: 1.5rem; }
```
vs
```css
.w-6,.s-6 { width: 1.5rem; }
.h-6,.s-6 { height: 1.5rem; }
```

It's less CSS in total and the behavior is exactly the same as adding the classes of the shortcut manually, no?
