### DISCUSSION TITLE
How to prevent UnoCSS to generate classes from <style> tag in vue SFC?

### DISCUSSION THREAD

**Discussion by fuale** [unocss/unocss#3102] [Q&A] [answered]
For example, i have following vue 3 SFC component:
```vue
<template>
  <div class="item"></div>
</template>

<style scoped>
.item {
  margin-top: 2rem;
  display: flex;
  position: relative;
}
</style>
```

Then in UnoCSS inspector i see following classes generated:
```css
/* layer: default */
.flex{display:flex;}
.relative{position:relative;}
```

And in final build it is also there.

![изображение](https://github.com/unocss/unocss/assets/36966275/0673db1e-852e-476b-b521-fa49f6b49050)
![изображение](https://github.com/unocss/unocss/assets/36966275/0365e90a-6a5d-4226-b212-82e07f554d78)
