### DISCUSSION TITLE
How to change appearance of every child with `selection:` variant?

### DISCUSSION THREAD

**Discussion by czernika** [unocss/unocss#3138] [Q&A]
UnoCSS v0.55.7 with preset-wind preset

```js
export default defineConfig({
    presets: [
        presetWind(), // imported
    ],
})
```

When I'm using `selection:bg-red-400` on body tag it generates following CSS

```css
.selection\:bg-red-400::selection {
  --un-bg-opacity: 1;
  background-color: rgba(248,113,113,var(--un-bg-opacity));
}
```

However same class in Tailwind will generate

```css
.selection\:bg-red-400 *::selection{
  --tw-bg-opacity: 1;
  background-color: rgb(248 113 113 / var(--tw-bg-opacity))
}
```

The difference here is the exact thing I'm looking for - UnoCSS will apply selection to this particular element while Tailwind for every element within. For now I have to stick with `[&_*::selection]:bg-red-400` but I wonder if the CSS is specifically modified for selection variant and is there any other not square-based "HTML" solution?
