### DISCUSSION TITLE
Nested theme color?

### DISCUSSION THREAD

**Discussion by ghost** [unocss/unocss#3434] [Q&A]
Currently, I have defined a theme like below
```ts
// uno.config.ts
theme: {
  colors: {
    "layer": {
      1: {
         "front": "#ffffff",
         "surface": "#ff0000"
       },
      2: {
         "front": "#ffffff",
         "surface": "#00ff00"
       }
    }
  }
}
```

and use it like
```html
<div class="bg-layer-1-surface text-layer-1-front">
  <p>first layer</p>
  <div class="bg-layer-2-surface text-layer-2-front">
    <p>second layer</p>
  </div>
</div>
```

I wonder if there is a way to simplify it like below?
```html
<div class="layer">
  <p>first layer</p>
  <div class="layer">
    <p>second layer</p>
  </div>
</div>
```

because I could do it with css like this
```css
.layer {
  background: #ff0000;
  color: #ffffff;
  .layer {
    background: #00ff00;
    color: #ffffff;
    /* more layer... */
  }
}
```
