### DISCUSSION TITLE
CSS-Scoping with wrapping Class- or ID-Selector #my-app {}

### DISCUSSION THREAD

**Discussion by deleonio** [unocss/unocss#3444] [Q&A] [answered]
Is it possible with UnoCss to enclose the generated CSS using any CSS selector?

```css
#my-app {
  .h4 {
    height: 1rem;
  }
}
```
