### DISCUSSION TITLE
Generated CSS file without any utility has some codes. What do they mean?

### DISCUSSION THREAD

**Discussion by LoTwT** [unocss/unocss#3513] [Q&A]
## description

After creating a new project and setting up unocss, directly build the project and the generated CSS file without any utility has some codes. What do they mean?

## additional context and questions

In modes such as `vue-scoped` and `shadow-dom`, the following codes will also be injected into the generated files or inline in js files. 

Do these codes should be split into one single file or reused as a single variable string if the codes should be kept?

## repro

repro steps:
  - create a new project and set up unocss with the default `global` mode
  - remove verbose components and CSS files
  - npm run build
  - see the generated CSS file in `dist/assets`

repro link: <https://stackblitz.com/edit/vitejs-vite-sjthdk?file=dist%2Fassets%2Findex-Gm3NSnFR.css>

```css
/* What do the following codes mean? */
*,
:before,
:after {
  --un-rotate: 0;
  --un-rotate-x: 0;
  --un-rotate-y: 0;
  --un-rotate-z: 0;
  --un-scale-x: 1;
  --un-scale-y: 1;
  --un-scale-z: 1;
  --un-skew-x: 0;
  --un-skew-y: 0;
  --un-translate-x: 0;
  --un-translate-y: 0;
  --un-translate-z: 0;
  --un-pan-x: ;
  --un-pan-y: ;
  --un-pinch-zoom: ;
  --un-scroll-snap-strictness: proximity;
  --un-ordinal: ;
  --un-slashed-zero: ;
  --un-numeric-figure: ;
  --un-numeric-spacing: ;
  --un-numeric-fraction: ;
  --un-border-spacing-x: 0;
  --un-border-spacing-y: 0;
  --un-ring-offset-shadow: 0 0 rgb(0 0 0 / 0);
  --un-ring-shadow: 0 0 rgb(0 0 0 / 0);
  --un-shadow-inset: ;
  --un-shadow: 0 0 rgb(0 0 0 / 0);
  --un-ring-inset: ;
  --un-ring-offset-width: 0px;
  --un-ring-offset-color: #fff;
  --un-ring-width: 0px;
  --un-ring-color: rgb(147 197 253 / 0.5);
  --un-blur: ;
  --un-brightness: ;
  --un-contrast: ;
  --un-drop-shadow: ;
  --un-grayscale: ;
  --un-hue-rotate: ;
  --un-invert: ;
  --un-saturate: ;
  --un-sepia: ;
  --un-backdrop-blur: ;
  --un-backdrop-brightness: ;
  --un-backdrop-contrast: ;
  --un-backdrop-grayscale: ;
  --un-backdrop-hue-rotate: ;
  --un-backdrop-invert: ;
  --un-backdrop-opacity: ;
  --un-backdrop-saturate: ;
  --un-backdrop-sepia: ;
}
::backdrop {
  --un-rotate: 0;
  --un-rotate-x: 0;
  --un-rotate-y: 0;
  --un-rotate-z: 0;
  --un-scale-x: 1;
  --un-scale-y: 1;
  --un-scale-z: 1;
  --un-skew-x: 0;
  --un-skew-y: 0;
  --un-translate-x: 0;
  --un-translate-y: 0;
  --un-translate-z: 0;
  --un-pan-x: ;
  --un-pan-y: ;
  --un-pinch-zoom: ;
  --un-scroll-snap-strictness: proximity;
  --un-ordinal: ;
  --un-slashed-zero: ;
  --un-numeric-figure: ;
  --un-numeric-spacing: ;
  --un-numeric-fraction: ;
  --un-border-spacing-x: 0;
  --un-border-spacing-y: 0;
  --un-ring-offset-shadow: 0 0 rgb(0 0 0 / 0);
  --un-ring-shadow: 0 0 rgb(0 0 0 / 0);
  --un-shadow-inset: ;
  --un-shadow: 0 0 rgb(0 0 0 / 0);
  --un-ring-inset: ;
  --un-ring-offset-width: 0px;
  --un-ring-offset-color: #fff;
  --un-ring-width: 0px;
  --un-ring-color: rgb(147 197 253 / 0.5);
  --un-blur: ;
  --un-brightness: ;
  --un-contrast: ;
  --un-drop-shadow: ;
  --un-grayscale: ;
  --un-hue-rotate: ;
  --un-invert: ;
  --un-saturate: ;
  --un-sepia: ;
  --un-backdrop-blur: ;
  --un-backdrop-brightness: ;
  --un-backdrop-contrast: ;
  --un-backdrop-grayscale: ;
  --un-backdrop-hue-rotate: ;
  --un-backdrop-invert: ;
  --un-backdrop-opacity: ;
  --un-backdrop-saturate: ;
  --un-backdrop-sepia: ;
}

```

**Comment by LoTwT** [comment]
I find it's related to `preset-mini`. By setting `presetUno({ preflight: false })` in the `uno.config.ts`, the codes above will not be generated. 

Unocss's doc says that `UnoCSS does not provide style resetting or preflight by default so not to populate your global CSS and also for maximum flexibility.` referring to [Browser Style Reset](https://unocss.dev/guide/style-reset#browser-style-reset).

 Is this behavior conflicted with the expected behavior that the doc describes?

**Comment by chu121su12** [comment]
Due to how css worked, it is quite difficult to do some of the partial overrides. Those variables is more like default values to make some utilities can be overriden by part with other utilities. You can see how it is implemented in ring and shadow utilities as compared to, say, margin and padding.

Those are also prefixed to reduce chance of clashing with other css libraries. Without any utilities generated, the rendered elements will look/behave the same even with those variables present (of course except if browsers/others are using the same variable names).

The difference with reset styles is that resets usually are there to change how browser renders the targetted element even if no utilities present.

**Reply by LoTwT** [reply]
Thanks! ♥️

According to your answer, these variables will not be in use if a project has no utility related to them, right? If it is right, could it be designed these variables be generated only when related utilities are in use? Is it necessary?

These variables seem to be generated into each CSS file when unocss's mode is `vue-scoped` or `shadow-dom`. Is this an expected behavior?

**Reply by chu121su12** [reply]
It should work but I haven't really tried it. I think the consideration is that the generated css is somewhat smaller not repeating the variables in each of the utilities.

Example in ring utilities, every base ring class would be:
```css
.ring-x {
  /* same in every ring */
  --un-ring-inset: ;
  --un-ring-offset-width: 0px;
  --un-ring-offset-color: #fff;
  --un-ring-width: 0px;
  --un-ring-color: rgb(147 197 253 / 0.5);
  --un-shadow: 0 0 rgb(0 0 0 / 0);

  /* actual ring override */
  --un-ring-width: x;
  --un-ring-offset-shadow: var(--un-ring-inset) 0 0 0 var(--un-ring-offset-width) var(--un-ring-offset-color);
  --un-ring-shadow: var(--un-ring-inset) 0 0 0 calc(var(--un-ring-width) + var(--un-ring-offset-width)) var(--un-ring-color);
  box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
}
```
