### DISCUSSION TITLE
How to uglify the generated class names when using UnoCSS?

### DISCUSSION THREAD

**Discussion by artiely** [unocss/unocss#4029] [Q&A]
How to uglify the generated class names when using UnoCSS?
like this
<img width="575" alt="image" src="https://github.com/user-attachments/assets/1b423f55-68dc-4a2c-a7b8-8a2026a08909">

**Comment by pdsuwwz** [comment]
My current approach is to put the class in a `xxx.module.scss` file. If you use `vite` and `scss`, the code will look similar to this:

```scss
// box.module.scss
.my-classname {
  --at-apply: 'line-height-24';
  --at-apply: 'flex flex-col';
  --at-apply: rounded-8 overflow-hidden;
}

```

Use in vue：

```ts
import StylesBox from './box.module.scss'

<div class={`${ StylesBox['my-classname'] }`}>
```

Configure vite.config.ts:

```ts
import { defineConfig } from 'vite'
import path from 'path'
import stringHash from 'string-hash'

export default defineConfig(({ mode }) => {
  return {
    // ...
    css: {
      modules: {
        generateScopedName: (name, filename, css) => {
          const f = filename.split('?')[0].split('.')[0]
          const file = path.basename(f)
          const hash = stringHash(css).toString(36).substr(0, 5);
          return `${file}_${name}_${hash}`
        }
      }
     // ...
    }
  }
})

```

Hopefully it helped you ~
