### DISCUSSION TITLE
How to write a class name that represents a nested css with css selectors?

### DISCUSSION THREAD

**Discussion by polarove** [unocss/unocss#4261] [Q&A] [answered]
e.g.
```html
<!-- This only takes affects with itself ->
<button class="active:color-red"/>
```

Expected
```html
<button class="active:span:color-gray" >
       <span>+</span>
</button>
```
Generated css should be
```css
button {
       &:active {
             span {
                  color: gray
             }
       }
}
```
