### ISSUE TITLE
Object Position Selector `object-[center_25%]` Does Not Generate Class

### ISSUE THREAD

**Issue by seeker-3** [unocss/unocss#1086]
`object-[center_25%]` is a valid tailwindcss selector

expected output:

```css
.object-\[center_25\%\] {
    object-position: center 25%;
}
```

However, unocss does not seem to recognize any custom object position selectors: `object-25%` `object-[25%]`

I'm using `presetWind` with sveltekit.

P.S. I found this package from the Dev Tools FM podcast. I absolutely love this package. Keep up the good work!
