### ISSUE TITLE
Feature request: support for opacity on color related utilities that use a `custom property` suffixed with `-rgb` as their value

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1168]
The combination of a custom property value like `bg-$custom-color` and opacity utility like `bg-opacity-50` does not work.

I want to propose that when a utility using a custom property is suffixed with `-rgb`, unocss generates values for the utility that are compatible with the related opacity utility.

# example

###### Input:
```html
<div style="--color-rgb: 255, 0, 0">
<div class="bg-$color-rgb bg-opacity-50">I'm half red!</div>
</div>
```

###### output:
```css
.bg-\$color-rgb { background: rgba( var(--color-rgb), var(--un-bg-opacity) ); }
```
