### ISSUE TITLE
Feature request: support for `:` in arbitrary variants

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1177]
The snippet below does not generate any css:

```
<div class="[[group-test]_*[group-test-hover]:hover]:bg-red-500" group-slideover>
  <div group-test>
    <div group-test-hover>
          Test
    </div>
  </div>
</div>
```

but when you add a space right before `:hover`, it generates the following css:

```css
/* layer: default */
[group-test] *[group-test-hover] :hover {
  --un-bg-opacity: 1;
  background-color: rgba(239, 68, 68, var(--un-bg-opacity));
}
```
