### ISSUE TITLE
unocss does not generate a proper selector for `children:space-y-2` 

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1246]
See the playground/html below. I expected all red squares to have space between them, but they do not. 
This did work in version v0.30.1. Somewhere between that version and v0.44.0 it broke

playground: https://uno.antfu.me/play/?html=DwEwlgbgBAxgFmANiATgUwHYC4DOAHAQxjQFoBPEgJgD4AoKKUSOhhp6AIwHMT0QSArAAYhUAO4kAjKLhSh1YAHpwEFq3ZRuvNP2GiJ0qLOkLlzeozOqL7NWxWaefQSPFyjc0yruMHW53puhsbySt42VnRhzEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wqgBdGTCkIA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA

###### HTML
```html
<div children:space-y-2>
  <div>
    <div bg-red-500 w-10 h-10></div>
    <div bg-red-500 w-10 h-10></div>
  </div>
  <div>
    <div bg-red-500 w-10 h-10></div>
    <div bg-red-500 w-10 h-10></div>
  </div>
</div>
```
###### config
```js
import {
  defineConfig,
  presetAttributify,
  presetUno
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify()
  ]
})

```

###### generated css:
```css
/* layer: default */
.w-10,
[w-10=""]{width:2.5rem;}
[h-10=""]{height:2.5rem;}
[children\:space-y-2=""]>:not([hidden])~:not([hidden])>*{--un-space-y-reverse:0;margin-top:calc(0.5rem * calc(1 - var(--un-space-y-reverse)));margin-bottom:calc(0.5rem * var(--un-space-y-reverse));}
.bg-red-500,
[bg-red-500=""]{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity));}
```
