### ISSUE TITLE
Using `part-[name-part]:` seems not to work

### ISSUE THREAD

**Issue by albizures** [unocss/unocss#1271]
Having `class="part-[xp-title]:bg-red"` unocss will generate:
```css
.part-\[xp-title\]\:bg-red(xp-title)::part{--un-bg-opacity:1;background-color:rgba(248,113,113,var(--un-bg-opacity));}
/*                            ^ this shouldn’t be here */
```
instead of:
```css
.part-\[xp-title\]\:bg-red::part(xp-title){--un-bg-opacity:1;background-color:rgba(248,113,113,var(--un-bg-opacity));}
```

here is a repro in stackblitz to check it out https://stackblitz.com/edit/vitejs-vite-zwd8q7?file=index.html
