### ISSUE TITLE
Can I use unocss api parse css?

### ISSUE THREAD

**Issue by shellingfordly** [unocss/unocss#1301]
because I want't to write atomic css on tag，do unocss provide api that parse atomic css?

can I use unocss parse atomic css to  native css

```css
.btn {
  p-10px;
  bg-pink;
}
/* use unocss parse */
.btn {
  padding: 10px;
  background: pink;
}
```
