### ISSUE TITLE
Preset Wind Missing Functionality `transition-[...]`

### ISSUE THREAD

**Issue by seeker-3** [unocss/unocss#1303]
example
`transition-[color_background-color_border-color]`

should generate
```css
.transition-\[color_background-color_border-color\] {
    transition-property: color background-color border-color;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms;
}
```

**Comment by chris-zhu** [comment]
use `transition-color,background-color,border-color`

**Comment by itpropro** [comment]
@chris-zhu I think this issue is to address the gap compared to tailwindcss that you can define arbitrary values for the `transition` property like `transition-[width]`m `transition-[height]` etc.. 
`transition-[width]` should compile to 

```css
.transition-\[width\] {
  transition-property: width;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
}
```

or something similar. I think it makes sense to have a general rule instead of listing all possibilities.
