### ISSUE TITLE
[type=button]  style preset in tailwind.css is not very friendly in some components

### ISSUE THREAD

**Issue by amihhs** [unocss/unocss#1315]
The property selector takes precedence over class, resulting in a strange look in some component libraries, which may be changed to the same as `@ unocss\ reset\ normalize.css`
```css
:where(button, input:is([type="button"], [type="reset"], [type="submit"])) {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```

Or does not use`: where` and `:is`
```css
button, input[type="button"], input[type="reset"], input[type="submit"] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```
