### ISSUE TITLE
UnoCSS works with SASS in dev but not in production

### ISSUE THREAD

**Issue by MuhammadM1998** [unocss/unocss#1361]
The engine works perfectly fine in a Nuxt project on dev mode, but on production classes applied by the `@apply` directive in a SASS doesn't work!

For example:

```css
.parent {
    // this works
    @apply bg-red; 

    .child {
      // this doesn't work
      @apply bg-blue; 

      > * {
        // this works !! wtf
        @apply md:max-w-3xl; 
      }

      .grand-child {
        // regular CSS works 
        background-image: url('<Some-Image-URL>'); 
      }
    }
}
```

This is my [project repo](https://github.com/MuhammadM1998/Groceyish/tree/main/Frontend-Nuxt) and this the [production version](https://groceyish.vercel.app/).
