### ISSUE TITLE
Feature Request: Provide extra responsive design prefix/modifiers

### ISSUE THREAD

**Issue by therealokoro** [unocss/unocss#1452]
@antfu hello 👋

So In my opinion, I think it would be nice to have some extra responsive design prefix for utility classes like provided in windicss.

Some what of a modifier for the responsive prefixes. 

Take `lg` as an example
```
<lg => smaller than this breakpoint
@lg => exactly this breakpoint range
```

## Example Usage

`<lg:p-2 @lg:p-3`

To generate

```css
@media (min-width: 1024px) and (max-width: 1279.9px) {
  .\@lg\:p-3 {
    padding: 0.75rem;
  }
}
@media (max-width: 1023.9px) {
  .\<lg\:p-2 {
    padding: 0.5rem;
  }
}
```

Example/idea gotten from [windicss](https://windicss.org/features/responsive-design.html)
