### ISSUE TITLE
有没有办法可以去掉那些用不到的css变量？

### ISSUE THREAD

**Issue by wtto00** [unocss/unocss#1456]
有没有办法可以去掉那些用不到的css变量？
Is there a way to get rid of those unneeded CSS variables?

---
```css
*, ::before, ::after {
    --un-rotate:0;
    --un-rotate-x:0;
    --un-rotate-y:0;
    --un-rotate-z:0;
    --un-scale-x:1;
    --un-scale-y:1;
    --un-scale-z:1;
    --un-skew-x:0;
    --un-skew-y:0;
    --un-translate-x:0;
    --un-translate-y:0;
    --un-translate-z:0;
    --un-pan-x:;
    --un-pan-y:;
    --un-pinch-zoom:;
    --un-scroll-snap-strictness:proximity;
    --un-ordinal:;
    --un-slashed-zero:;
    --un-numeric-figure:;
    --un-numeric-spacing:;
    --un-numeric-fraction:;
    --un-border-spacing-x:0;
    --un-border-spacing-y:0;
    --un-ring-offset-shadow:0 0 rgba(0, 0, 0, 0);
    --un-ring-shadow:0 0 rgba(0, 0, 0, 0);
    --un-shadow-inset:;
    --un-shadow:0 0 rgba(0, 0, 0, 0);
    --un-ring-inset:;
    --un-ring-offset-width:0;
    --un-ring-offset-color:#fff;
    --un-ring-width:0;
    --un-ring-color:rgba(147, 197, 253, 0.5);
    --un-blur:;
    --un-brightness:;
    --un-contrast:;
    --un-drop-shadow:;
    --un-grayscale:;
    --un-hue-rotate:;
    --un-invert:;
    --un-saturate:;
    --un-sepia:;
    --un-backdrop-blur:;
    --un-backdrop-brightness:;
    --un-backdrop-contrast:;
    --un-backdrop-grayscale:;
    --un-backdrop-hue-rotate:;
    --un-backdrop-invert:;
    --un-backdrop-opacity:;
    --un-backdrop-saturate:;
    --un-backdrop-sepia:;
}
::backdrop {
    --un-rotate:0;
    --un-rotate-x:0;
    --un-rotate-y:0;
    --un-rotate-z:0;
    --un-scale-x:1;
    --un-scale-y:1;
    --un-scale-z:1;
    --un-skew-x:0;
    --un-skew-y:0;
    --un-translate-x:0;
    --un-translate-y:0;
    --un-translate-z:0;
    --un-pan-x:;
    --un-pan-y:;
    --un-pinch-zoom:;
    --un-scroll-snap-strictness:proximity;
    --un-ordinal:;
    --un-slashed-zero:;
    --un-numeric-figure:;
    --un-numeric-spacing:;
    --un-numeric-fraction:;
    --un-border-spacing-x:0;
    --un-border-spacing-y:0;
    --un-ring-offset-shadow:0 0 rgba(0, 0, 0, 0);
    --un-ring-shadow:0 0 rgba(0, 0, 0, 0);
    --un-shadow-inset:;
    --un-shadow:0 0 rgba(0, 0, 0, 0);
    --un-ring-inset:;
    --un-ring-offset-width:0;
    --un-ring-offset-color:#fff;
    --un-ring-width:0;
    --un-ring-color:rgba(147, 197, 253, 0.5);
    --un-blur:;
    --un-brightness:;
    --un-contrast:;
    --un-drop-shadow:;
    --un-grayscale:;
    --un-hue-rotate:;
    --un-invert:;
    --un-saturate:;
    --un-sepia:;
    --un-backdrop-blur:;
    --un-backdrop-brightness:;
    --un-backdrop-contrast:;
    --un-backdrop-grayscale:;
    --un-backdrop-hue-rotate:;
    --un-backdrop-invert:;
    --un-backdrop-opacity:;
    --un-backdrop-saturate:;
    --un-backdrop-sepia:;
}
```

我不认为我需要这些css变量，是否有一个配置选项可以删除这些？
I don't think I need these CSS variables, is there a configuration option to remove these?

---
```css
.c-black {
    --un-text-opacity: 1;
    color: rgba(0,0,0,var(--un-text-opacity));
}
```
是否可以简写为下边这种？
Can I just write it as the following
```css
.c-black {
    color: rgba(0,0,0);
}
```
