### ISSUE TITLE
How to programmatically use `transformer-directives`?

### ISSUE THREAD

**Issue by kidonng** [unocss/unocss#1470]
Given the following program:

```js
import { createGenerator, presetUno, transformerDirectives } from 'unocss'

const generator = createGenerator({
	presets: [presetUno()],
	transformers: [transformerDirectives()]
})
const {css} = await generator.generate(`
	.test {
		@apply text-2xl;
	}
`)
console.log(css)
```

Output:

```css
/* layer: preflights omitted */
/* layer: default */
.text-2xl{font-size:1.5rem;line-height:2rem;}
```

The same CSS processed through Vite plugin:

```css
/* Stuff omitted */
.test{font-size:1.5rem;line-height:2rem}
```

Is there a way to use `transformer-directives` standalone?

**Comment by chris-zhu** [comment]
> Is there a way to use `transformer-directives` standalone?

I think it can't work alonely. `transformer-directives` used by `uno` context, you have to provide `uno` context to use.
And you can check test code to learn this workflow.

https://github.com/unocss/unocss/blob/628c29c366d787e58a1ccd18b3b18cf352031e62/test/transformer-directives.test.ts#L12-L40

**Comment by kidonng** [comment]
Thanks for the pointer. I got it working:

```js
import { createGenerator, presetUno } from "unocss";
import { transformDirectives } from "@unocss/transformer-directives";
import MagicString from "magic-string";

const generator = createGenerator({
  presets: [presetUno()],
});
const transform = async (css) => {
  const code = new MagicString(css);
  await transformDirectives(code, generator, {});
  return code.toString();
};

const css = await transform(`
	.test {
		@apply text-2xl;
	}
`)
console.log(css)
```

Result:

```css
.test {
        font-size:1.5rem;line-height:2rem;
}
```
