### ISSUE TITLE
Breakpoints normalisation required

### ISSUE THREAD

**Issue by Triloworld** [unocss/unocss#1586]
This won't work and need additionally test and fix:
```css
      breakpoints: {
        'small-screen': '320px', /* Dash in middle */
        sm: '640px',
        md: '768px',
        '4k': '1536px', /* Number first */
        '[x]': '1999px', /* Special char */
      },
```
Example that is tested and working
```css
      breakpoints: {
        xs: '320px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        xxl: '1536px',
      },
```

Working on TailwindCSS schema and not working in UnoCss implementation.
