### ISSUE TITLE
Only apply hover styles when support

### ISSUE THREAD

**Issue by Miles-C** [unocss/unocss#1681]
This solves the ["sticky hover" problem](https://css-tricks.com/solving-sticky-hover-states-with-media-hover-hover/) where tapping something that includes a hover style on mobile will persist that hover style until tapping elsewhere.

copy this code for your unocss.config.ts
```js
// unocss.config.ts
variants: [
    (matcher) => {
      // The prefix cannot start with "-" or "hover", you can customize the prefix.
      if (!matcher.startsWith('&hover:')) return matcher
      return {
        // slice `hover:` prefix and passed to the next variants and rules
        matcher: matcher.slice(7),  // The 7 here represents the number of characters in the prefix.
        parent: [`@media (hover: hover) and (pointer: fine)`],
        selector: (s) => `${s}:hover`,
      }
    },
  ],
```

when using:
```html
<!-- Use prefix: &hover -->
<div class="&hover:text-red &hover:dark:text-blue">Hello World</div>
```

CSS Generated：
```css
@media (hover: hover) and (pointer: fine)
.\&hover\:text-red:hover {
    --un-text-opacity: 1;
    color: rgba(248,113,113,var(--un-text-opacity));
}

@media (hover: hover) and (pointer: fine)
.dark .\&hover\:dark\:text-blue:hover {
    --un-text-opacity: 1;
    color: rgba(96,165,250,var(--un-text-opacity));
}
```

Tip: Do not use with normal `hover:`, because hover will overwrite `&hover:` 
```html
<!-- hover:text-blue --working, &hover:text-red --no woking -->
<div class="&hover:text-red hover:text-blue">Hello World</div>
```
