### ISSUE TITLE
How to write a media-query custom rule?

### ISSUE THREAD

**Issue by jiangyijie27** [unocss/unocss#17]
For example, to match this className:

```html
<div className="mb_20_24-500_1280" />
```

These need to be generated by `rules`:

```css
@media(min-width: 500px) {
  margin-bottom: 20px;
}
@media((min-width: 500px) and (max-width: 1280px)) {
  margin-bottom: calc(20px + (24 - 20) / (1280 - 500) * (100vw - 500px));
}
@media(min-width: 1280px) {
  margin-bottom: 24px;
}
```

So the `margin-bottom` of this element will change smoothly from `20px` to `24px` when window width is between 500 and 1280.

I realize one of the advantages `unocss` has over `tailwindcss` is that I can write my own parser rule, but it's not able to add media-query rule now, right?
