### ISSUE TITLE
`__VITE_PUBLIC_ASSET__hash__` doesn't get replaced in the generated output

### ISSUE THREAD

**Issue by equt** [unocss/unocss#1850]
> I've created a minimal reproducible example [here](https://github.com/equt/reference-public-in-css).

For the class `bg-[url(/not-an-image.jpg)]`, it works correctly in the development mode, while outputs

```css
.bg-\[url\(\/not-an-image\.jpg\)\] {
  --un-url: url(__VITE_PUBLIC_ASSET__032ad66c__);
  background-image: var(--un-url);
}
```

in the build mode.

Seems like the generated CSS didn't go through Vite's post-process but instead retrieved directly via the chunk hash? Just note it here for further debugging.
