### ISSUE TITLE
attributify not working on JSX.Element

### ISSUE THREAD

**Issue by JustGreg** [unocss/unocss#1897]
It looks like attributify doesn't work with JSX.Element in solid.js

```tsx
import type { JSX } from 'solid-js';
import { Component } from 'solid-js';

const Input = (props: JSX.HTMLAttributes<HTMLInputElement>) => <input border="~ green" {...props} type="text" />;

const App: Component = () => {
  return (
    <div bg="red-100">
      Test:
      <Input text="7" bg-dark rounded class="ml-3" />
    </div>
  );
};

export default App;
```

this code produce the following css:
```css
/* layer: default */
.ml-3{margin-left:0.75rem;}
.bg-dark{--un-bg-opacity:1;background-color:rgba(34,34,34,var(--un-bg-opacity));}
[bg~="red-100"]{--un-bg-opacity:1;background-color:rgba(254,226,226,var(--un-bg-opacity));}
[border~="\~"]{border-width:1px;border-style:solid;}
[border~="green"]{--un-border-opacity:1;border-color:rgba(74,222,128,var(--un-border-opacity));}
```

`text="7"` and `rounded` isn't in the list and `bg-dark` is generated as classname but is used as attribute.

genearated html code:
```html
<div bg="red-100">
  Test:
  <input border="~ green" type="text" text="7" bg-dark="true" rounded="true" class="ml-3">
</div>
```
