### ISSUE TITLE
icons does not work with nextjs

### ISSUE THREAD

**Issue by marcustut** [unocss/unocss#190]
I'm using Nextjs12 and `@unocss/cli`, everything works fine except for icons.

Looking into the css files and generated css, I think it's more of a NextJS issue rather than Unocss's issue, however just how to open this issue and see what others think about this.

**Generated CSS (uno.css)**
```css
/* layer: icons */
.i-mdi\:alarm{--un-icon:url("data:image/svg+xml;utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1em' height='1em' preserveAspectRatio='xMidYMid meet' viewBox='0 0 24 24'%3E%3Cpath d='M12 20a7 7 0 0 1-7-7a7 7 0 0 1 7-7a7 7 0 0 1 7 7a7 7 0 0 1-7 7m0-16a9 9 0 0 0-9 9a9 9 0 0 0 9 9a9 9 0 0 0 9-9a9 9 0 0 0-9-9m.5 4H11v6l4.75 2.85l.75-1.23l-4-2.37V8M7.88 3.39L6.6 1.86L2 5.71l1.29 1.53l4.59-3.85M22 5.72l-4.6-3.86l-1.29 1.53l4.6 3.86L22 5.72z' fill='currentColor'/%3E%3C/svg%3E");mask:var(--un-icon) no-repeat;mask-size:100% 100%;-webkit-mask:var(--un-icon) no-repeat;-webkit-mask-size:100% 100%;background-color:currentColor;height:1em;width:1em;}
/* layer: default */
.bg-dark-400{--un-bg-opacity:1;background-color:rgba(34,34,34,var(--un-bg-opacity));}
.text-3xl{font-size:1.875rem;line-height:2.25rem;}
.text-dark-500{--un-text-opacity:1;color:rgba(31,31,31,var(--un-text-opacity));}
.flex{display:flex;}
.h-100vh{height:100vh;}
.justify-center{justify-content:center;}
.items-center{align-items:center;}
```

Here, we can see that the data-uri is properly generated, if I copy the data uri and render it on https://www.site24x7.com/tools/datauri-to-image.html, we can see an icon.

However, when nextjs bundles the files, I think it does some processing on CSS files, when I inspect the CSS in browser, it looks like this 
![image](https://user-images.githubusercontent.com/59773847/144107112-0d323861-f8a2-41f1-adeb-9f7e3429562b.png)
I did go and find this generated static .svg file, it does exists on the Filesystem and is a valid SVG. However, it somehow doesn't work in the browser.
