### ISSUE TITLE
Whether the rule mode of css variable can be changed

### ISSUE THREAD

**Issue by itmanyong** [unocss/unocss#2044]
### features
- 1.The specific class name style content does not contain css variables
- 2.The automatically injected css variables will also be meaningless and will not be injected
### codes
- default
```css
.text-green {
    --un-text-opacity: 1; // Css variables will be generated
    color: rgba(74, 222, 128, var(--un-text-opacity));
}
```
- close css variable
```css
.text-green {
   // No css variables
    color: rgba(74, 222, 128, 1);  // Specific values
}
```
### other
![1111](https://user-images.githubusercontent.com/53500371/210602126-01fdb544-52fd-4f00-9911-0a261cb50045.png)
