### ISSUE TITLE
vscode: show values on pixel

### ISSUE THREAD

**Issue by zirbest** [unocss/unocss#2340]
### Clear and concise description of the problem

unocss
```css
/* layer: default */
.text-xl {
  font-size: 1.25rem;
  line-height: 1.75rem;
}
```

### Suggested solution

tailwindcss
```css
font-size: 1.125rem/* 18px */;

.text-xl {
    font-size: 1.125rem/* 18px */;
}
```

show calculated values on pixel
