### ISSUE TITLE
After the vite build is enabled with cssCodeSplit:false, it is used with unocss. In a single css file packed out, the scoped styles of asynchronous components are placed at the top of the stylesheet, changing the css priority

### ISSUE THREAD

**Issue by xut0793** [unocss/unocss#2410]
### UnoCSS version

^0.50.6

### Describe the bug

因为打算构建微前端子项目，项目所有css打包成单个样式文件，所以 vite.config.js 中 build 选项中配置了 cssCodeSplit: false。
但是搭配 unocss 后，异步组件 scoped 的样式被放在了单个样式表顶部，使得生产环境中 css 优先级改变了，样式错乱。

如果项目中不使用 unocss ，样式构建正常， scoped 的样式被放在了单个样式表尾部。

Because you want to build the micro-front-end subproject, all the css of the project is packaged into a single style file, so the build option in ite.config.js configs cssCodeSplit: false.
However, when paired with unocss, the styles of scoped asynchronous component are placed on top of a single style sheet, resulting in a change in css priority and a confusion of styles in the production environment.
If unocss is not used in the project, the styles are built properly and the scoped styles are placed at the end of a single style sheet.

```css
#app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}
@media (prefers-color-scheme: light) {
  :root {
    color: #213547;
    background-color: #fff;
  }
  a:hover {
    color: #747bff;
  }
  button {
    background-color: #f9f9f9;
  }
}
.read-the-docs[data-v-f01b5731] {
  color: #888;
}
.logo[data-v-0adc6510] {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 0.3s;
}
.logo[data-v-0adc6510]:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue[data-v-0adc6510]:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
.async-router-yellow[data-v-dfa771b6] {
  color: #ff0;
}
.async-component-red[data-v-8080fde4] {
  color: red;
}
```
但是使用 unocss 构建后，样式错乱，scoped 的样式被放在了单个样式表顶部
```css
.async-router-yellow[data-v-dfa771b6] {
  color: #ff0;
}
.async-component-red[data-v-8080fde4] {
  color: red;
}
*,
:before,
:after {
}
...省略
```

### Reproduction

[https://github.com/xut0793/vite-cssCodeSplit-false-unocss-bug](https://github.com/xut0793/vite-cssCodeSplit-false-unocss-bug

### System Info

依赖信息：
```json
  "dependencies": {
    "vue": "^3.2.45",
    "vue-router": "^4.1.6"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "typescript": "^4.9.3",
    "unocss": "^0.50.6",
    "vite": "^4.1.0",
    "vue-tsc": "^1.0.24"
  }
```
vite.config.js
```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import Unocss from "unocss/vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), Unocss()],
  build: {
    cssCodeSplit: false,
    target: "esnext",
  },
});
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
