### ISSUE TITLE
Wrong peer dependency when installing with Yarn

### ISSUE THREAD

**Issue by devunt** [unocss/unocss#2431]
### UnoCSS version

0.50.6

### Describe the bug

When installing unocss with Yarn, it warns that `vite` was requested by `@unocss/vite`, but `unocss` didn't provide it.

```
~/w/rezero develop• 2.3s ❱ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @unocss/astro@npm:0.50.6 doesn't provide vite (pd448d), requested by @unocss/vite
➤ YN0002: │ unocss@npm:0.50.6 [7eda2] doesn't provide vite (pb07dc), requested by @unocss/vite
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 232ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 409ms
➤ YN0000: Done with warnings in 1s 851ms
~/w/rezero develop• 2.1s ❱ 
```

Possible solution: add `vite` as optional peer dependency to `unocss` and `@unocss/astro`.

Possible workaround: add following directives to `.yarnrc.yaml` makes warnings go away.

```yaml
packageExtensions:
  unocss@*:
    peerDependencies:
      vite: ^2.9.0 || ^3.0.0-0 || ^4.0.0
    peerDependenciesMeta:
      vite:
        optional: true
  "@unocss/astro@*":
    peerDependencies:
      vite: ^2.9.0 || ^3.0.0-0 || ^4.0.0
    peerDependenciesMeta:
      vite:
        optional: true
```

### Reproduction

Having `package.json` fields with

```json
"devDependencies": {
    "unocss": "^0.50.6",
    "vite": "^4.2.1",
}
```

### System Info

Yarn v3.5.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
