### ISSUE TITLE
cssnano + @unocss/transform-directives causes an 'Cannot split a chunk that has already been edited' error

### ISSUE THREAD

**Issue by tysian** [unocss/unocss#2581]
### UnoCSS version

0.51.12

### Describe the bug

Using:
* Vite 4.3.2
* SASS 1.62.1
* UnoCSS 0.51.12
* cssnano 6.0.1

Using nested at-rules inside sass file causes error.
```scss
.example {
  // Doesn't matter which one is used
  @apply text-red-500;
  // --at-apply: text-red-500;

  @screen lt-md {
    // This causes an error
    @apply text-green-500;

    // Adding this instead doesn't work at all
    // --at-apply: text-blue-500;
  }
}
// Using this example https://github.com/unocss/unocss/blob/main/packages/transformer-directives/README.md#screen
// But it also doesn't work if cssnano is enabled
.example-2 {
  .grid {
    --uno: grid grid-cols-1;
  }
  @screen md {
    .grid {
      --uno: grid-cols-1;
    }
  }
  @screen lg {
    .grid {
      --uno: grid-cols-3;
    }
  }
}
```
[plugin:unocss:transformers:default] Cannot split a chunk that has already been edited (0:52 – "@screen lt-md{.example{@apply ")

![image](https://user-images.githubusercontent.com/16374473/236627648-2ada371a-7480-48d9-bcfc-9949759c3149.png)

Error appears when using postcss plugin: **cssnano**.
Using `--at-apply` or `--uno` does nothing.
 

I know it might be a duplicate of https://github.com/unocss/unocss/issues/2022 but seems like different things caused the same error.

### Reproduction

Reproduction:
https://stackblitz.com/edit/vitejs-vite-5anp17?file=src/example.scss

Comment out cssnano plugin in `postcss.config.cjs` to remove this error.

### System Info

Windows 10 64-bit
Chrome 113.0.5672.63
Package manager: npm & pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
