### ISSUE TITLE
Apply directives do not work as expected in `svelte-scoped`

### ISSUE THREAD

**Issue by scheatkode** [unocss/unocss#2680]
### UnoCSS version

0.52.4

### Describe the bug

Custom styles defined in imported CSS files are not transformed when using apply directives. For instance, the following, when defined in `app.s?css`:

```css
div {
  --at-apply: text-black;
}
```

Renders to:

```css
div {
  --at-apply: text-black;
}
```

Instead of:

```css
div {
  --a-text-opacity: 1;
  color: rgba(0,0,0,var(--a-text-opacity));
}
```

---

Furthermore, `theme()` is not recognized, even inside components.

```svelte
<p>...</p>

<style>
  p {
    color: theme("colors.a_color.a_shade");
  }
</style>
```

Renders to:

```css
p.s-<hash> {
  color: theme("colors.black");
}
```

Instead of:

```css
p.s-<hash> {
  color: #000;
}
```

---

I'm reporting this as a bug since these break the expectations set by the `svelte-scoped` mode prior to the rewrite leading to `@unocss/svelte-scoped`. But don't get me wrong, I think `@unocss/svelte-scoped` is a major step forward. Thanks to all the maintainers involved !

### Reproduction

The above examples should be sufficient, but please do tell if a full reproduction is required.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
