### ISSUE TITLE
Uno generates redundant styles for each breakpoint for `{bp}:container`

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2709]
### UnoCSS version

0.52.7

### Describe the bug

Currently if we add `md:container` class, Uno will generate this styles:
```css
@media (min-width: 768px){
.md\:container{max-width:768px;}
}
@media (min-width: 1024px){
.md\:container{max-width:1024px;}
}
@media (min-width: 1280px){
.md\:container{max-width:1280px;}
}
@media (min-width: 1536px){
.md\:container{max-width:1536px;}
}
```
But it is enought to have this one:
```css
@media (min-width: 768px){
.md\:container{max-width:768px;}
}
```

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC2IBcMD2AdgC4JiECmATugHzAD04EtQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCZgEpRQA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CoderMonkie** [comment]
why this issue closed...

---

In my case, I don`t need any `.container` class，but unocss（actually tailwindcss）generates them（each breakpoint）automatically，
And，I dont know how to disable it..
(while could disable in tailwindcss`s config)

Now, I use a global class to overwrite it, like:
```css
.container {
  max-width: none;
}
```

---

If there`s any other resolutions, please let me know.

---
