### ISSUE TITLE
Hover being triggered when disabled even with specified disabled: variants

### ISSUE THREAD

**Issue by ZainW** [unocss/unocss#2713]
### UnoCSS version

0.52.7

### Describe the bug

In tailwind and their product tailwind ui hover states are not triggered when hovering over an item that is disabled when disabled styles are specified.

In unocss when an item is disabled specifies disabled: classes, they are still overridden by hover on hover.

this breaks feature parity from moving from tailwind to uno when using presetUno

uno from what i can tell provides no configuration or speicifc default behaviour when dealing with this

### Reproduction

https://stackblitz.com/edit/unocss-unocss-rxp1nt?file=src%2FApp.vue for uno

https://play.tailwindcss.com/9eEGbmAT2c tailwind (for reference)

### System Info

Macos
arc
Vite + Vue 3

happens in the playgrounds specified

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I can confirm it's an ordering bug.

For

```html
<button disabled class="hover:text-red-300 text-blue-700 disabled:text-purple-900"> Look at me</button>
```

Tailwind outputs:

```css
.text-blue-700 {
  --tw-text-opacity: 1;
  color: rgb(29 78 216 / var(--tw-text-opacity));
}

.hover\:text-red-300:hover {
  --tw-text-opacity: 1;
  color: rgb(252 165 165 / var(--tw-text-opacity));
}

.disabled\:text-purple-900:disabled {
  --tw-text-opacity: 1;
  color: rgb(88 28 135 / var(--tw-text-opacity));
}

```

UnoCSS outputs ([play](https://unocss.dev/play/?html=DwIwrgLhD2B2AEATAlgZwIYgDYFNHwGMt1VUBeAIgAtoA3HAJwC4IcAPCAWgb04GYADAPisOnbGBycA7EKRpMuRC3ZcADmAZrcnAJxCKAPngAZaNADW8dBHgBbHMAD04KHENA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbjlJtKgBccADa-FKyEO4AlBIC9IzM7Jw80QC6BgpRBkA&css=Q&options=N4XyA)):

```css
/* layer: default */
.disabled\:text-purple-900:disabled{--un-text-opacity:1;color:rgba(88,28,135,var(--un-text-opacity));}
.hover\:text-red-300:hover{--un-text-opacity:1;color:rgba(252,165,165,var(--un-text-opacity));}
.text-blue-700{--un-text-opacity:1;color:rgba(29,78,216,var(--un-text-opacity));}
```
