### ISSUE TITLE
(@unocss/webpack): class util with variant prefixes in webpack preset does not work

### ISSUE THREAD

**Issue by zoeyzhao19** [unocss/unocss#2794]
### UnoCSS version

0.53.3

### Describe the bug

Class util like `sm:bg-red-500` does not work in  webpack project with `@unocss/webpack`
```html
<template>
  <div class="flex justify-center">
    <p class="sm:bg-red-500">The background should be red but it does not</p>
  </div>
</template>
```
The style append to body is
```css
@media (min-width: 320px) {.sm:bg-red-500{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity))} }
```

The expected css result is 
```css
@media (min-width: 320px) { .sm\:bg-red-500{--un-bg-opacity:1;background-color:rgba(239,68,68,var(--un-bg-opacity))} }
```
Maybe something got wrong when write to webpack assets without further escape for the generated css 

### Reproduction

- git clone [repo](https://github.com/zoeyzhao19/unocss-webpack-issue) or view online [sandbox](https://codesandbox.io/p/github/zoeyzhao19/unocss-webpack-issue/master?workspaceId=8a7a8b86-fa11-43ae-9a2d-fc45b02e677c)
-  run `pnpm dev` 

### System Info

- OS: Windows 10 10.0.22621

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
