### ISSUE TITLE
Styles sometimes don't apply with Svelte Scoped and Svelte 4

### ISSUE THREAD

**Issue by scheatkode** [unocss/unocss#2818]
### UnoCSS version

0.53.4

### Describe the bug

There are some edge cases when using Svelte 4 where styles are not generated for some components. I have yet to find the source of the issue but managed to provide a repro showcasing the problem; *extracted and stripped down from the real app*.

Currently, a workaround is to downgrade Svelte to 3.59.2.

But here comes more weird part. The diffs below are a few examples of changes that make the issue disappear in the repro.

```diff
diff --git a/src/routes/technical-studies.section.svelte b/src/routes/technical-studies.section.svelte
index b40e081..27c676c 100644
--- a/src/routes/technical-studies.section.svelte
+++ b/src/routes/technical-studies.section.svelte
@@ -6,9 +6,6 @@
 		<h4 class="text-primary text-lg font-bold tracking-wide">
 		</h4>
 
-		<h3 class="my-4 text-4xl font-bold text-gray-100">
-		</h3>
-
 		<h4 class="my-4 text-xl leading-relaxed text-gray-100">
 		</h4>
 
```

```diff
diff --git a/src/routes/+page.svelte b/src/routes/+page.svelte
index fa56246..4e581e4 100644
--- a/src/routes/+page.svelte
+++ b/src/routes/+page.svelte
@@ -1,6 +1,5 @@
 <script lang="ts">
 	import EnvironmentalRegulationSection from "./environmental-regulation.section.svelte";
-	import TechnicalStudiesSection from "./technical-studies.section.svelte";
 </script>
 
 <EnvironmentalRegulationSection />
```

### Reproduction

https://github.com/scheatkode/unocss-weirdness-repro

#### Expected

![image](https://github.com/unocss/unocss/assets/29172448/131a5ee1-ba1d-45a4-b0c6-85c464d5e120)

#### Actual

![image](https://github.com/unocss/unocss/assets/29172448/2275b818-1df5-4694-881e-3e74bcfcd397)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
I tried to reproduce but couldn't get `Actual` to show, only `Expected`. Could it be a browser issue?
That being said I have a site that looks like `Actual` when not using the Svelte-scoped preprocess option.

**Comment by scheatkode** [comment]
Even weirder if this turns out to be a case of *"works on my machine"*.

> Could it be a browser issue?

I just tested on both Firefox and Chromium, and the issue persists, even with `npm` instead of `pnpm`, and Node 20 instead of 18.

Meanwhile I dug a dig deeper and unlike what I mentioned in #2811, I'm starting to think it **is** a mismatch issue, just not that of the hash; looking [at the implementation](https://github.com/unocss/unocss/blob/72d4cffabed71684e068fdc546e6526550c55063/packages/svelte-scoped/src/_preprocess/transformClasses/hash.ts#L2), it seems to me `hash()` has a predictable enough output that shouldn't cause mismatches.

I just noticed that (in my faulty case) `svelte-scoped` loads the stylesheet of the wrong component, hence why this diff suddenly makes things work.

```diff
diff --git a/src/routes/+page.svelte b/src/routes/+page.svelte
index fa56246..4e581e4 100644
--- a/src/routes/+page.svelte
+++ b/src/routes/+page.svelte
@@ -1,6 +1,5 @@
 <script lang="ts">
 	import EnvironmentalRegulationSection from "./environmental-regulation.section.svelte";
-	import TechnicalStudiesSection from "./technical-studies.section.svelte";
 </script>
 
 <EnvironmentalRegulationSection />
```

![image](https://github.com/unocss/unocss/assets/29172448/6602f48f-97dd-45eb-adec-e0325de0cbe5)

![image](https://github.com/unocss/unocss/assets/29172448/7f820223-d6f2-4e5d-a7b5-f37bcced7c2c)

<details>
<summary>The full compiled CSS</summary>

```css
._mx-auto_de6akb {
 margin-left:auto;
 margin-right:auto
}
._my-4_de6akb {
 margin-top:1rem;
 margin-bottom:1rem
}
._mt-4_de6akb {
 margin-top:1rem
}
._max-w-screen-xl_de6akb {
 max-width:1280px
}
._flex_de6akb {
 display:flex
}
._btn_de6akb {
 flex-shrink:0;
 cursor:pointer;
 -webkit-user-select:none;
 user-select:none;
 border-radius:0.5rem;
 padding-top:0.75rem;
 padding-bottom:0.75rem;
 padding-left:1rem;
 padding-right:1rem;
 font-size:0.875rem;
 line-height:1.25rem;
 font-weight:600;
 line-height:1.625;
 letter-spacing:0.025em;
 text-transform:uppercase;
 --un-text-opacity:1;
 color:rgba(249,250,251,var(--un-text-opacity));
 text-decoration:none;
 --un-shadow:var(--un-shadow-inset) 0 4px 6px -1px var(--un-shadow-color, rgba(0,0,0,0.1)),var(--un-shadow-inset) 0 2px 4px -2px var(--un-shadow-color, rgba(0,0,0,0.1));
 box-shadow:var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow)
}
._flex-col_de6akb {
 flex-direction:column
}
._justify-center_de6akb {
 justify-content:center
}
._gap-10_de6akb {
 grid-gap:2.5rem;
 gap:2.5rem
}
._gap-2_de6akb {
 grid-gap:0.5rem;
 gap:0.5rem
}
._rounded-full_de6akb {
 border-radius:9999px
}
._btn-primary_de6akb {
 --un-bg-opacity:1;
 background-color:rgba(151,75,220,var(--un-bg-opacity))
}
._btn-primary_de6akb:hover {
 --un-bg-opacity:1;
 background-color:rgba(135,57,200,var(--un-bg-opacity))
}
._text-4xl_de6akb {
 font-size:2.25rem;
 line-height:2.5rem
}
._text-lg_de6akb {
 font-size:1.125rem;
 line-height:1.75rem
}
._text-xl_de6akb {
 font-size:1.25rem;
 line-height:1.75rem
}
._font-bold_de6akb {
 font-weight:700
}
._leading-relaxed_de6akb {
 line-height:1.625
}
._tracking-wide_de6akb {
 letter-spacing:0.025em
}
._text-gray-100_de6akb {
 --un-text-opacity:1;
 color:rgba(243,244,246,var(--un-text-opacity))
}
@media(prefers-reduced-motion: no-preference) {
 ._btn_de6akb {
  transition-property:color,background-color,border-color,outline-color,text-decoration-color,fill,stroke;
  transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration:150ms
 }
}
@media(min-width: 768px) {
 ._md\:flex-row_de6akb {
  flex-direction:row
 }
}
.s-nPEbjpu1bsE5 {
}
```
</details>

This is `TechnicalStudiesSection`'s stylesheet.
