### ISSUE TITLE
默认预设与 Tailwind 不兼容，失去继承属性。

### ISSUE THREAD

**Issue by dufu1991** [unocss/unocss#2961]
### UnoCSS version

0.54.2

### Describe the bug

我使用默认预设，继承自 [@unocss/preset-wind](https://alfred-skyblue.github.io/unocss-docs-cn/presets/wind) 时发现这个预设并没有与 Tailwind 一致。在文件 packages/reset/tailwind-compat.css 和 packages/reset/tailwind.css 中 border-color 是固定写为 #e5e7eb 。
```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #e5e7eb; /* 2 */
}
```

但是 Tailwind 中是这样的。https://github.com/tailwindlabs/tailwindcss/blob/05e307bb6c562884877ea52b0d147bcecc4df3f6/src/css/preflight.css
```css
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: theme('borderColor.DEFAULT', currentColor); /* 2 */
}
```

这样就导致 border-color 与 Tailwind 不兼容，并且失去了继承。

### Reproduction

https://github.com/tailwindlabs/tailwindcss/blob/05e307bb6c562884877ea52b0d147bcecc4df3f6/src/css/preflight.css

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://github.com/tailwindlabs/tailwindcss/blob/4f0bb0b73ad7fb82e626ca7c2ddced0d0f0edc7c/stubs/config.full.js#L84C57-L84C57

If you not change the default color theme, `borderColor.DEFAULT === #e5e7eb`

**Comment by dufu1991** [comment]
However, Tailwind also has a `currentColor` utility, which allows the border color to inherit the text color when no border color is set. When I created the project using `pnpm create stdf@latest`, I noticed that the border color of the "+10" button is inconsistent when selecting Tailwind and UnoCSS separately.

This is because Tailwind compiles to:

```css
*, ::before, ::after {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: currentColor;
}
```

However, UnoCSS compiles to:

```css
*, ::before, ::after {
    box-sizing: border-box;
    border-width: 0;
    border-style: solid;
    border-color: #e5e7eb;
}
```

In the Tailwind version, the `border-color` is set to `currentColor`, which means it will inherit the text color. On the other hand, the UnoCSS version directly sets the `border-color` to `#e5e7eb`.

I still hope to have a `currentColor` as a fallback solution.
