### ISSUE TITLE
`.transform` class is not compatible with `tailwindcss`

### ISSUE THREAD

**Issue by 171h** [unocss/unocss#2970]
### UnoCSS version

0.54.3

### Describe the bug

# video

https://github.com/unocss/unocss/assets/40647432/c19c40cb-299a-4975-99f4-530b5d5ede6e

## Toggle component https://ui.nuxtlabs.com/forms/toggle

`.transform` class in unocss
```
translateX(var(--un-translate-x)) translateY(var(--un-translate-y)) translateZ(var(--un-translate-z)) rotate(var(--un-rotate)) rotateX(var(--un-rotate-x)) rotateY(var(--un-rotate-y)) rotateZ(var(--un-rotate-z)) skewX(var(--un-skew-x)) skewY(var(--un-skew-y)) scaleX(var(--un-scale-x)) scaleY(var(--un-scale-y)) scaleZ(var(--un-scale-z))
```

`.transform` class in tailwindcss

```
translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
```

### Reproduction

.

### System Info

---------
- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      modules, experimental, css, colorMode, nitro, app, pwa, devtools
- Runtime Modules:  @vueuse/nuxt@10.3.0, @unocss/nuxt@0.54.3, @pinia/nuxt@0.4.11, @nuxtjs/color-mode@3.3.0, @vite-pwa/nuxt@0.1.0, @nuxthq/ui@2.7.0-28194972.fe95ffe
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
I think this happened if you use the styles without its reset.

![image](https://github.com/unocss/unocss/assets/379924/607de5d9-d36f-4d35-b567-a0dd388f13a5)

Can you confirm the bug still happen if you inject this reset style:

```css
*, ::after, ::before {
    --tw-translate-x: 0;
    --tw-translate-y: 0;
    --tw-translate-z: 0;
    --tw-rotate: 0;
    --tw-rotate-x: 0;
    --tw-rotate-y: 0;
    --tw-rotate-z: 0;
    --tw-skew-x: 0;
    --tw-skew-y: 0;
    --tw-scale-x: 1;
    --tw-scale-y: 1;
    --tw-scale-z: 1;
}
```
