### ISSUE TITLE
[@unocss/postcss] Breakpoints not compiled in proper order in CSS module

### ISSUE THREAD

**Issue by jaredblase** [unocss/unocss#3023]
### UnoCSS version

0.55.2

### Describe the bug

There is incorrect precedence in @unocss/postcss when compiling variants using screen breakpoints. For example:

`@apply sm:bg-red-500 md:bg-blue-500 lg:bg-white xl:bg-black`

will produce

```css
@media (min-width: 1280px)
.home_test__6pzJC {
    --un-bg-opacity: 1;
    background-color: rgba(0,0,0,var(--un-bg-opacity));
}

@media (min-width: 1024px)
.home_test__6pzJC {
    --un-bg-opacity: 1;
    background-color: rgba(255,255,255,var(--un-bg-opacity));
}

@media (min-width: 768px)
.home_test__6pzJC {
    --un-bg-opacity: 1;
    background-color: rgba(59,130,246,var(--un-bg-opacity));
}

@media (min-width: 640px)
.home_test__6pzJC {
    --un-bg-opacity: 1;
    background-color: rgba(239,68,68,var(--un-bg-opacity));
}
```

making red the default color as long as the screen is bigger than 640px

### Reproduction

https://codesandbox.io/p/sandbox/blissful-violet-hgz4jm

### System Info

System: Windows 11
Browser: Google Chrome
Framework: NextJS 13

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
