### ISSUE TITLE
Nested (Arbitrary?) variant group handling

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3051]
### UnoCSS version

latest

### Describe the bug

I'm not sure if this is really a bug, but I do think the current handling of nested variant groups is not correct.

Let's take an example:
```ts
shortcuts: {
  'btn': '[&.foo]:(p-2 [&.bar]:(m-2 p-0))'
}
```
❌is currently compiled into `[&.foo]:[&.bar]:...`
Which is equivalent to
```scss
.btn.foo {
  padding: 0.5rem;
}
.btn.bar {
  margin: 0.5rem;
  padding: 0;
}
```

✅However, it's pretty clear that `bar` is nested in `foo` variant group, hence IMO it should be compiled to something like this
```scss
.btn.foo {
  padding: 0.5rem;
  
  &.bar {
    margin: 0.5rem;
    padding: 0;
  }
}
```

where they are very different.

Is the current way intended or a missing condition in the implementation?

### Reproduction

Can provide one if needed, but I think the above is pretty clear.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
