### ISSUE TITLE
`transformerVariantGroup` not working with `postcss` for `next.js` 13 (app directory)

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3192]
### UnoCSS version

latest

### Describe the bug

Hi, sorry if this is marked somewhere, as I tried my best to search through but seems no one has raised this. Seems adding `transformers` into `uno.config.ts` has no effect when using `postcss` plugin? How do I make it support `transformerVariantGroup`?

Otherwise things like `after:(xxx1 xxx2)` won't work and it will be a nightmare to write `after:xxx1 after:xxx2`

### Reproduction

The same as in `examples` folder, I can't get the codesandbox running up due to limit on their disk space

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by greenhat616** [comment]
Maybe all transformers is not work?
In my test, `transformerCompileClass` is  not work too.

**Comment by greenhat616** [comment]
Follow this issue: https://github.com/unocss/unocss/issues/3089, postcss can't handle tsx, jsx files.

And, if we use webpack version, these is no config, which can compile perfectly like Vite.
Followed this issue: https://github.com/unocss/unocss/issues/2195, I configured `content.include/exclude`
But either `css, scss` is not processed, or some `tsx` files' classNames can't be observed. :(

**Comment by xsjcTony** [comment]
But `@unocss/webpack` (guided by https://unocss.dev/integrations/next#next-js) is not working with `app` directory in `next.js 13`, so seems the `@unocss/postcss` is the only solution there, but it does not support `transformers` 😥.

**Comment by greenhat616** [comment]
> But `@unocss/webpack` (guided by https://unocss.dev/integrations/next#next-js) is not working with `app` directory in `next.js 13`, so seems the `@unocss/postcss` is the only solution there, but it does not support `transformers` 😥.

Yes. You're right. It not work in Webpack completely.

I use this config in `uno.config.ts`:
```ts
content: {
    pipeline: {
      include: [/src\/.*\.(s?css|[jt]sx?)$/],
      exclude: []
    }
  },
```

My App dirs:
```
app tree app
├── [lang]
│   ├── Header.module.scss
│   ├── Header.tsx
│   ├── layout.tsx
│   └── page.tsx
└── favicon.ico
```

It works in `layout.tsx`, `Header.tsx` and `*.scss/css`` files. But it's not work in `Page.tsx`. I don't know why.

**Maybe, the only approach to get it work, is `@unocss/cli`?**
Related: https://github.com/unocss/unocss/issues/1880#issuecomment-1319745724

**Comment by xsjcTony** [comment]
Ah yeah... that's a bit frustrating. Honestly the postcss support is already pretty good, since most of things are working out of the box after following the official next.js 13 example. I just want to know how transformers really working (or are they even supported) in postcss way🤣

**Comment by xsjcTony** [comment]
no-stale

**Comment by RebeccaStevens** [comment]
Ahh, so if the issue is that `@unocss/postcss` can't transform the HTML, would I use a different integration in conjunction with the postcss one to simply to do this transform?

I'm using the postcss integration in my Nuxt project as I need support for outputting different layers in different locations (e.g. using `@unocss my_layer`), which the `@unocss/nuxt` integration doesn't currently support.

If I use the Nuxt integration with `mode: "global"`, but don't add `uno.css` anywhere, and continue to use the postcss integration to generate the actually CSS, would there be any unintended side effects?

**Comment by Simon-He95** [comment]
One solution is to use the [vscode unot](https://github.com/Simon-He95/unot) plugin, which supports automatically converting `hover:(xx yy) to hover:xx hover:yy` when you save.

**Comment by xsjcTony** [comment]
Yeah that's cool. Unfortunately I'm a JetBrains user😥

**Comment by Simon-He95** [comment]
> Yeah that's cool. Unfortunately I'm a JetBrains user😥

This is unfortunate, but I'd like to try to see if I can fix this on unocss. Would you mind providing a simple demo?

**Comment by Simon-He95** [comment]
Due to the lack of a minimal reproducible demo, I will temporarily close this issue. Please feel free to open it when a reproducible demo is provided.

**Comment by ackvf** [comment]
I managed to get the output from the transformer and add it to the token list for processing, however, I was not able to get the transformed classes back to the elements, so the css would never apply.

e.g.

source: (tsx component)
```
<div className="hover:(bg-neutral-500 ring-2 ring-white)" />
```

output:
```
// css
hover:bg-neutral-500 { background-color: ...}
hover:ring-2 { ... }
hover:ring-white
```

```
// html is still the same
<div className="hover:(bg-neutral-500 ring-2 ring-white)" />
```

**Comment by solonovamax** [comment]
> Due to the lack of a minimal reproducible demo, I will temporarily close this issue. Please feel free to open it when a reproducible demo is provided.

@Simon-He95 Here's a minimal reproducible sample using the compile class transformer with postcss & parcel:

---
- [unocss-postcss-3192-minimal-sample.tar.gz](https://github.com/user-attachments/files/18272168/unocss-postcss-3192-minimal-sample.tar.gz)
- [unocss-postcss-3192-minimal-sample.zip](https://github.com/user-attachments/files/18272169/unocss-postcss-3192-minimal-sample.zip)
---
<details>
<summary>File Contents</summary>

`package.json`:
```json
{
  "name": "unocss-parcel-test",
  "version": "1.0.0",
  "description": "Minimal sample for unocss/unocss#3192",
  "scripts": {
    "build": "parcel build --no-optimize src/**/*.html"
  },
  "author": "solonovamax",
  "devDependencies": {
    "@unocss/cli": "^0.65.3",
    "@unocss/postcss": "^0.65.3",
    "@unocss/preset-uno": "^0.65.3",
    "@unocss/transformer-compile-class": "^0.65.3",
    "parcel": "^2.13.3",
    "postcss": "^8.2.1",
    "unocss": "^0.65.3"
  }
}
```
`unocss.config.ts`:
```ts
import transformerCompileClass from '@unocss/transformer-compile-class';
import { defineConfig, presetUno } from 'unocss';

export default defineConfig({
  cli: {
    entry: {
      patterns: [ 'src/**/*.html' ],
      outFile: 'dist/main.css',
    },
  },
  content: {
    filesystem: [ 'src/**/*.html' ],
    pipeline: {
      include: [ 'src/**/*.html' ]
    }
  },
  presets: [ presetUno() ],
  transformers: [ transformerCompileClass() ]
});
```
`src/index.html`:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Minimal Sample For unocss/unocss#3192</title>
        <link rel="stylesheet" href="index.css">
    </head>
    <body>
        <div class=":uno: p-4 text-center sm:text-left">
            <div class=":uno: py-4 text-sm font-bold hover:text-red"/>
        </div>
    </body>
</html>
```
`src/index.css`:
```css
@layer base, components, utilities;

@layer base {
    @unocss preflights;
}

@layer utilities {
    @unocss default;

    @unocss;
}

@layer components {

}
```
`.postcssrc`:
```json
{
    "plugins": {
        "@unocss/postcss": true
    }
}
```

</details>

---

#### Expected Output
```css
@layer base {
    /* unocss preflight stuff... */
}

@layer components;

@layer utilities {
    .uno-owbhgs {
        padding: 1rem;
        text-align: center;
    }

    .uno-ysx7jn {
        padding-top: 1rem;
        padding-bottom: 1rem;
        font-size: 0.875rem;
        line-height: 1.25rem;
        font-weight: 700;
    }

    .uno-ysx7jn:hover {
        --un-text-opacity: 1;
        color: rgb(248 113 113 / var(--un-text-opacity)) /* #f87171 */;
    }

    @media (min-width: 640px) {
        .uno-owbhgs {
            text-align: left;
        }
    }
}
```
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Minimal Sample For unocss/unocss#3192</title>
        <link rel="stylesheet" href="/index.3e1d3457.css">
    </head>
    <body>
        <div class="uno-owbhgs">
            <div class="uno-ysx7jn">
            </div>
        </div>
    </body>
</html>
```

#### Actual Output

```css
@layer base {
    /* unocss preflight stuff... */
}

@layer components;

@layer utilities {
    .p-4 {
        padding: 1rem;
    }
  
    .py-4 {
        padding-top: 1rem;
        padding-bottom: 1rem;
    }
  
    .text-center {
        text-align: center;
    }
  
    .text-sm {
        font-size: .875rem;
        line-height: 1.25rem;
    }
  
    .hover\:text-red:hover {
        --un-text-opacity: 1;
        color: rgb(248 113 113 / var(--un-text-opacity));
    }
  
    .font-bold {
        font-weight: 700;
    }
  
    @media (width >= 640px) {
        .sm\:text-left {
          text-align: left;
        }
    }
}
```
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Minimal Sample For unocss/unocss#3192</title>
        <link rel="stylesheet" href="/index.3e1d3457.css">
    </head>
    <body>
        <div class=":uno: p-4 text-center sm:text-left">
            <div class=":uno: py-4 text-sm font-bold hover:text-red">
            </div>
        </div>
    </body>
</html>
```

---

Please reopen the issue.
