### ISSUE TITLE
[preset-wind] Media breakpoint prefix ignored when using `prefix` config 

### ISSUE THREAD

**Issue by kaorukobo** [unocss/unocss#3322]
### UnoCSS version

0.57.2

### Describe the bug

With the reproduction below, when running the command:

`./node_modules/.bin/unocss --preflights false sample.html`

the output `uno.css` should be:

```css
.tw\:my-1{margin-top:0.25rem;margin-bottom:0.25rem;}
@media (min-width: 768px){
.tw\:md\:my-1{margin-top:0.25rem;margin-bottom:0.25rem;}
}
```

but the actual output is:

```css
.tw\:my-1{margin-top:0.25rem;margin-bottom:0.25rem;}
```

### Reproduction

https://gist.github.com/kaorukobo/416eccfaddeb654b3325c837a81612be

and also can be reproduced by the following commands:

```bash
npm i unocss

cat > sample.html <<HTML
<div class="tw:my-1 tw:md:my-1"></div>
HTML

cat > uno.config.ts <<TS
import { defineConfig } from 'unocss'
import presetWind from '@unocss/preset-wind'

export default defineConfig({
    presets: [
        presetWind({prefix: 'tw:'}),
    ],
    preflights: [],
})
TS

./node_modules/.bin/unocss --preflights false sample.html

cat *.css
```

### System Info

```
$ node -v
v20.8.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
