### ISSUE TITLE
Unocss has packaged all JS variables in the Vue file

### ISSUE THREAD

**Issue by Sk-0515** [unocss/unocss#3371]
### UnoCSS version

^0.57.7

### Describe the bug

When I developed using Vue template, I defined JS variables, but unocss also packaged JS variables.

### Reproduction

```ts
 //vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue';
import UnoCSS from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    UnoCSS()
  ]
})
```
```ts
//uno.config.ts
export default defineConfig({
  presets: [presetMini()],
});`
```
```vue
<template>
  <view> 123333 </view>
</template>
 <script lang="ts" setup>
import { ref } from "vue";
const relative = ref("");
const visible = ref(false);
</script>
<style scoped>
.a {
  color: cadetblue;
 position: sticky;
}
</style>
```
```css
.relative{position:relative;}
.sticky{position:sticky;}
.visible{visibility:visible;} 
```

### System Info

vue3 + ts + vite

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dicarbene** [comment]
You mean unocss should not scan the <script> code and generating the corresponding class names right?

**Comment by Sk-0515** [comment]
> You mean unocss should not scan the <script> code and generating the corresponding class names right?

Yes, the style label should also be the same. Is there any good solution?

**Comment by Simon-He95** [comment]
> > You mean unocss should not scan the <script> code and generating the corresponding class names right?你的意思是 unocss 不应该扫描
> 
> @Dicarbene Yes, the style label should also be the same. Is there any good solution?是的，样式标签也应该相同。有什么好的解决方案吗？

try to use it
```
<!-- @unocss-skip-start -->
<!-- `text-red` will not be extracted -->
<p class="text-red">
  Red
</p>
<!-- @unocss-skip-end -->
```

**Comment by Dicarbene** [comment]
https://github.com/unocss/unocss/issues/2761 Perhaps this method can be helpful, although it may become a bit messy on a larger scale. However, such unwanted scanning scenarios are quite rare. Even if they do occur, they should not affect your program's functionalities?

**Comment by Sk-0515** [comment]
I have written a Transformer code,but it has no effect in<script>,<style>can filter!

```typescript
import type { SourceCodeTransformer } from 'unocss';
export default function fillterStyleTag(): SourceCodeTransformer {
    return {
        name: 'my-fillterStyleTag',
        enforce: 'pre', // enforce before other transformers
        idFilter(id) {
            return /\.(vue)$/.test(id);
        },
        async transform(code, id, ctx) {
            const data = code.original.replace(
               /<(style|script)[^>]*>(.*?)<\/(style|script)>/gs,
                (v) => `<!-- @unocss-skip-start -->\n${v}\n<!-- @unocss-skip-end -->\n`
            );
            code.overwrite(0, code.original.length, data);
        }
    };
}
``` 
###app.css
```css
.px {
  padding-left: 1rem;
  padding-right: 1rem;
}
.m-3\.5rpx {
  margin: 3.5rpx;
}
.bg-\[\#565555\] {
  --un-bg-opacity: 1;
  background-color: rgb(86 85 85 / var(--un-bg-opacity));
}
.b {
  border-width: 1px;
}
.text-\[\#653662\] {
  --un-text-opacity: 1;
  color: rgb(101 54 98 / var(--un-text-opacity));
}
.relative {
  position: relative;
}
.w-\[50\%\] {
  width: 50%;
}
.visible {
  visibility: visible;
}
``` 
### app.vue
```vue
<template>
  <view class="content">
    <image class="logo" src="/static/logo.png" />
    <view class="m-3.5rpx bg-[#565555] w-[50%] text-[#653662]">3333</view>
    <view :style="{ width: 30 + 'px' }">123456</view>
  </view>
</template>
<script lang="ts" setup>
import { ref } from "vue";
const relative = ref("");
const visible = ref(false);
</script>
<style>
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.logo {
  overflow: hidden;
  height: 200rpx;
  width: 200rpx;
  margin-top: 200rpx;
  margin-left: auto;
  margin-right: auto;
  margin-bottom: 50rpx;
}
```
