### ISSUE TITLE
Bug: shadow does not take into account custom color

### ISSUE THREAD

**Issue by Scrum** [unocss/unocss#3390]
### UnoCSS version

0.57.7

### Describe the bug

Shadow does not take into account custom color

**index.html**
```html
<div class="shadow-[0_2px_10px] shadow-blackA7">test</div>
```

**unocss.config.js**
```js
import { defineConfig } from 'unocss'

export default defineConfig({
  theme: {
    colors: {
      blackA7: "hsla(0, 0%, 0%, 0.169)"
    }
  }
})
```

**output css**
```css
.shadow-\[0_2px_10px\] {
  --un-shadow: 0 2px 10px;
  box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow),
    var(--un-shadow);
}
[shadow-blackA7=''] {
  --un-shadow-opacity: 0.169;
  --un-shadow-color: hsla(0, 0%, 0%, var(--un-shadow-opacity));
}
```

> Please note, in the variable `--un-shadow: 0 2px 10px;` color value is missing.

**Expected**
```css
--un-shadow: 0 2px 10px var(--un-shadow-color);
```

### Reproduction

[reproduction link](https://uno.antfu.me/play/?html=ATA8BMEsDdgZwBYENwHsDuBaA2gBgPoBMADgB74CMuZAuvMmlgEYA2SAxgNYCCA7AHwAXAKZxBoAPRRo-AFBA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHBgALVCFQAuRCtVxmEMdFZ7lhwwCMxw5gGsAggHY9AInWs7CgAwAaOF8AUkCQsIA6AEYANgBOAEp3A1VSAzTVTlIEoA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

### System Info

Browser: Firefox

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
