### ISSUE TITLE
error caused by inconsistency in `box-shadow` between UnoCSS v0.58.0 and v0.57.7

### ISSUE THREAD

**Issue by Mini-ghost** [unocss/unocss#3439]
### UnoCSS version

v0.58.0

### Describe the bug

I've encountered an issue while using UnoCSS in my project. The following `box-shadow` definition in my project:

```html
<div class="shadow-[0px_8px_8px_0px_var(--box-shadow-color)]"></div>
```

However, in version v0.58.0, the generated CSS differs from the previous version v0.57.7, resulting in a display problem in my styles. 

Here's the CSS generated by v0.58.0:

```css
.shadow-\[0px_8px_8px_0px_var\(--box-shadow-color\)\] {
  --un-shadow: 0px 8px 8px 0px var(--box-shadow-color) var(--un-shadow-color);
  box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow),
    var(--un-shadow);
}
```

Whereas, this was the CSS generated by v0.57.7:

```css
.shadow-\[0px_8px_8px_0px_var\(--box-shadow-color\)\] {
  --un-shadow: 0px 8px 8px 0px var(--box-shadow-color);
  box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow),
    var(--un-shadow);
}
```

This is the difference

```diff

.shadow-\[0px_8px_8px_0px_var\(--box-shadow-color\)\] {
-  --un-shadow: 0px 8px 8px 0px var(--box-shadow-color);
+  --un-shadow: 0px 8px 8px 0px var(--box-shadow-color) var(--un-shadow-color);
   box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow),
     var(--un-shadow);
}

```

If this is expected, please feel free to close this issue

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIkAsEgPYDuAtANoAMADgB4D6AHNfY5bRAgE4AURRARnlSLZchIjDxw87AJQBddAD5gAenAQFAKCA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSSjj4CAFygANpOBoj%2BlMUAlAC6QS2CQA&css=HQZwFghgJg9g7gWgMYFcBOaCmA7ALgAgG8AofM-AegCp8AGYAVgA5hb8qLTyEEVsFw0eAC46ABwAe%2BJpOmzasgG4Q0ACh4AjGBIGRYiJDAA2MNAEp8ytTz66hB46bMBuLmS07B%2B0VfW9%2BaACW2ADmCDAAZhEgmLh2%2BmYANJYqfrZBofHwSSnW-llwLsQAvsTEoHrwCJgSYphIBCTklDT0DADswO3snM02-F4i4lIyI-JKqZraBciO5q7NHgU%2Bk-kZYZHRsQU5vv0I6zvJe-mDha6lxEA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

### System Info

- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Package Manager:  pnpm@8.11.0
- Runtime Modules:  @unocss/nuxt@0.58.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
