### ISSUE TITLE
CSS transformer does not visit nested rules

### ISSUE THREAD

**Issue by jods4** [unocss/unocss#3573]
### UnoCSS version

0.58.5

### Describe the bug

`theme(..)` is replaced by appropriate constant color in CSS rules that are included in my Vite project but it's left untouched when using CSS nesting.

You can checkout live playground link below but basically:
```css
/* Input */
.top {
  color: theme('colors.red.400');
  
  .nested {
    color: theme('colors.red.400');
  }
}

/* Output */
.top {
  color: #f87171;
  
  .nested {
    color: theme('colors.red.400');
  }
}
```

### Reproduction

https://unocss.dev/play/?html=Q&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRwjx8iKAMmPCQcnyc4DQAIrB0LLAAblAhYRGRAAIxlHGQwOmZ2TS5NGhF4CXlCYKCxKKpsnKYFtAj8ooqarDqABSS0jQTUABcoADaOtJbkUwWkIjhtGuRmhKg7tB8m5F0qJGggQC6Xu86kAAWKYcCm2W0iih2Opx%2BfyskXurBIyGg6jSxBQfAy6nAoF%2B5Ro61hKFYmGgFx0gS8TgMAO2u28zkQ-koCwAlF5HD5jKZGJZrHYmSyaRS3B4ltTpJAmITwJsAIwAOgATHzpExUPB7t9TNxIOsQFBODKfsBicCXsydJ9pC0sjk8lqqcbLW0OoVitY%2BryzUFGYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUGOyCwAb21gUWZdw1xyvABQByZOe7oxlRmIAsABm-2AlADcJmBi9AiYCMzGpqZOFlBWNggO8S5uUV6%2BAcGmAL7aBUA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC5JMBTAXyA

### System Info

Reproduces in playground, see link above

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
