### ISSUE TITLE
Issue with UnoCSS theme function returning non-color value

### ISSUE THREAD

**Issue by FE-runner** [unocss/unocss#3617]
### UnoCSS version

0.58.5

### Describe the bug

When using UnoCSS with Scss, there is an inconsistency in how colors are handled when retrieved using the theme function. While variables defined directly as colors ($v1: blue;) behave as expected, those retrieved through the theme('colors.blue.500') function are not recognized as colors in certain Sass functions such as mix, transparentize, and rgba. This inconsistency leads to errors when attempting to manipulate colors retrieved via the theme function.

### Reproduction

```scss
  $v1: blue;
  $v2: theme('colors.blue.500');
  .a1 {
    background: $v1; //ok
    background: $v2; //ok
    background: mix($v1, #fff, 0.5); //ok
    background: transparentize($v1, 0.5); //ok
    background: rgba($v1, 0.5); //ok
    background: mix($v2, #fff, 0.5); //no $color1: theme("colors.blue.500") is not a color.
    background: transparentize($v2, 0.5); //no $color1: theme("colors.blue.500") is not a color.
    background: rgba($v2, 0.5); //no $color1: theme("colors.blue.500") is not a color.
  }
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
