### ISSUE TITLE
`transformer-directives` transforms opacities incorrectly

### ISSUE THREAD

**Issue by CNSeniorious000** [unocss/unocss#3784]
### UnoCSS version

v0.60.0

### Describe the bug

```css
* {
  --uno: bg-black/5
}
```

Is transformed into

```css
* {
  --un-bg-opacity:1;
  background-color:rgb(0 0 0 / var(--un-bg-opacity));
}
```

### Reproduction

In the UnoCSS Playground:

1. add `transformerDirectives()` to `transformers` in _Config_ panel
2. add `* { --uno: bg-black/5 }` to  _Custom CSS_ panel

And you will see the background is totally black.

### System Info

Edge, Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
