### ISSUE TITLE
Nuxt Build Error: [unocss:transformers:undefined] Cannot split a chunk that has already been edited

### ISSUE THREAD

**Issue by moldypenguins** [unocss/unocss#3980]
### UnoCSS version

0.61.0

### Describe the bug

I am getting this error when trying to build. I am unsure why the section children are causing the issue.

Nuxt Build Error: [unocss:transformers:undefined] Cannot split a chunk that has already been edited (0:1130 – "@screen lg{section{--uno:p-10}section .component{--uno:flex-basis-47.5%}section ")

See also: #2022 #2418 #2581 

```scss
/* With Build Error */

section {
  --uno: m-0 p-6 w-full flex flex-col justify-start items-center border-r-8;

  .component {
    --uno: relative flex-basis-full;
  }
  .component-narrow {
    --uno: py-0 px-8;
  }
}
@screen lg {
  section {
    --uno: p-10;

    .component {
      --uno: flex-basis-48%;
    }
    .component-narrow {
      --uno: p-0;
    }
  }
}
```

```scss
/* No Build Error */

section {
  --uno: m-0 p-6 w-full flex flex-col justify-start items-center border-r-8;

  .component {
    --uno: relative flex-basis-full;
  }
  .component-narrow {
    --uno: py-0 px-8;
  }
}
@screen lg {
  section {
    --uno: p-10;
  }
}
```

EDIT:
I have tracked it down to where the scss is included.
```js
// nuxt.config.ts
css: ['@unocss/reset/tailwind.css','~/assets/styles/main.scss'],
```
OR
```vue
<!-- app.vue -->
<style lang="scss">
@use '@/assets/styles/main.scss';
</style>
```

### Reproduction

[https://stackblitz.com/edit/nuxt-starter-cjjxxr](https://stackblitz.com/edit/nuxt-starter-cjjxxr)

### System Info

Windows 11 / Ubuntu 22.04

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
