### ISSUE TITLE
Inconsistent Styles Between Development and Production in UnoCSS with Nuxt

### ISSUE THREAD

**Issue by Mini-ghost** [unocss/unocss#4079]
### UnoCSS version

0.61.9, 0.62.2

### Describe the bug

I have been using UnoCSS in Nuxt, and I really appreciate the convenience it brings. However, I have recently encountered some issues where there are significant inconsistencies between development and production environments, and at times, it even affects the build process.

Here is a relatively minor but challenging issue that I encountered in my component:

```scss
.prose {
  --bg-code-block: black;

  pre {
    @apply text-sm;
    @apply bg-[var(--bg-code-block)];
    @apply ring-1 ring-gray/10 hover:ring-2 hover:ring-gray/30;
    @apply p-6;
    @apply rounded-2 overflow-x-auto;
    @apply transition-all duration-300;
  }
}
```

During development, everything works perfectly as expected, as seen through the browser's inspection tool:

```css
.prose pre {
    font-size: 0.875rem;
    line-height: 1.25rem;
    background-color: var(--bg-code-block) /* var(--bg-code-block) */;
    --un-ring-width: 1px;
    --un-ring-offset-shadow: var(--un-ring-inset) 0 0 0 var(--un-ring-offset-width) var(--un-ring-offset-color);
    --un-ring-shadow: var(--un-ring-inset) 0 0 0 calc(var(--un-ring-width) + var(--un-ring-offset-width)) var(--un-ring-color);
    box-shadow: var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);
    --un-ring-color: rgb(156 163 175 / 0.1) /* #9ca3af */;
    padding: 1.5rem;
    overflow-x: auto;
    border-radius: 0.5rem;
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 150ms;
    transition-duration: 300ms;
}
```

However, after building for production, some styles disappear:

```css
.prose pre {
    font-size: .875rem;
    line-height: 1.25rem;
    --un-ring-width: 1px;
    --un-ring-offset-shadow: var(--un-ring-inset) 0 0 0 var(--un-ring-offset-width) var(--un-ring-offset-color);
    --un-ring-shadow: var(--un-ring-inset) 0 0 0 calc(var(--un-ring-width) + var(--un-ring-offset-width)) var(--un-ring-color);
    box-shadow: var(--un-ring-offset-shadow),var(--un-ring-shadow),var(--un-shadow);
    --un-ring-color: rgb(156 163 175 / .1);
    transition-property: all;
    transition-timing-function: cubic-bezier(.4,0,.2,1);
    transition-duration: .15s;
    transition-duration: .3s;
}
```

As you can see, `background-color`, `padding`, `overflow-x`, and `border-radius` are all missing after the build.

I am not sure if I am doing something wrong, and if so, I would greatly appreciate any guidance on the correct approach.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-4v5vh9?file=unocss.config.ts,nuxt.config.ts,app.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
