### ISSUE TITLE
Feature: icon() function in custom CSS

### ISSUE THREAD

**Issue by jods4** [unocss/unocss#4111]
### Clear and concise description of the problem

Sometimes you want to put an icon into a background, especially where it's difficult / undesirable / impossible to introduce additional elements, such as adding icons into forms inputs or styling a native checkbox input.

### Suggested solution

It would be nice to be able to apply just the inline image data-url into custom CSS styles.
I think the intuitive way to do this would be to provide a `icon()` function that is replaced by unocss, similar to `theme()`.

`icon('ph:user')` would be replaced by the data-url generated by this line in icons preset: 
```js
const url = `url("data:image/svg+xml;utf8,${encodeSvgForCss(svg)}")`
```

Example usage: 
```css
input[type=checkbox]:checked {
  background: icon('ph:check') no-repeat, white
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Why wouldn't you use directives?

```css
input[type=checkbox]:checked {
  --uno: i-ph-check;
  font-size: 1em;
}
```
