### ISSUE TITLE
proposal: support dynamic layer (and layer order?) in rules 

### ISSUE THREAD

**Issue by olets** [unocss/unocss#4131]
### Clear and concise description of the problem

I'd like to be to have rules which put CSS in an arbitrary layer based on the class name, and set the layer order based on the class name. Just like we can currently use the rule regex to set parent, selector, property, and value, I'd like to be able to use the rule regex to set layer and to set that layer's order.

### Suggested solution

I've thought of three possible solutions

1. Have the `layers` config generate a block at-rule.
    _Supports a subset of possible needs_

    ```js
    export default defineConfig({
      layers: {
        stuff: 1,
        things: 2,
      },
      rules: [
        [
          /^m-([a-z]+)-(\d+)$/,
          ([, layer, size], { symbols }) => ({
            [symbols.parent]: `@layer ${layer}`,
            margin: `${size / 4}rem`
          }),
        ],
      ],
      // must leave `outputToCssLayers` false
    })
    ```
    ```html
    <div class="m-stuff-4"></div>
    ```
    ```diff css
    + @layer stuff, things;

    @layer stuff {
      .m-stuff-4 {
        margin: 1rem;
      }
    }
    ```
    Downsides:
    - `symbols.parent` can't be used for anything else in the same rule
    - `outputToCssLayers` can't be used (from UnoCSS's perspective, the CSS is in the `default` layer)
    - layer ordering can't itself be dynamic

    Benefits:
    - smallest change
3. Teach `symbols` about layers.
    🌟 _I like this forth best_
    ```js
    export default defineConfig({
      layers: {
        stuff: 1,
        things: 2,
      },
      rules: [
        [
          /^m-([a-z]+)-(\d+)$/,
          ([, layer, size], { symbols }) => ({
            [symbols.layer]: layer,
            margin: `${size / 4}rem`
          }),
        ],
      ],
      // optional: add `outputToCssLayers: true,`
    })
    ```
    ```html
    <div class="m-stuff-4"></div>
    ```
    ```css
    /* layer: stuff */
    .m-stuff-4 {
      margin: 1rem;
    }
    ```
    Downsides:
    - Two handles for controlling layer, one in the rule's second argument and one in the third argument.

    Benefits:
    - can use `symbols.parent` for other things
    - can choose to use `outputToCssLayers` or not
    - potential for teaching symbols.layers about order
        🌟🌟 _I like this third best_
        ```js
        export default defineConfig({
          layers: {
            stuff: 1,
            things: 2,
          },
          rules: [
            [
              /^m-([a-z]+)(-\d+)?-(\d+)$/,
              ([, layer, layerOrder, size], { symbols }) => {
                return {
                  [symbols.layer]: [layer, layerOrder], // would also accept `[symbols.layer]: [layer]`. maybe also accept `[symbols.layer]: layer`? or maybe use an object instead?
                  margin: `${size / 4}rem`,
                }
              },
            ],
          ],
          // optional: add `outputToCssLayers: true,`
        })
        ```
        ```html
        <div class="m-stuff-4"></div>
        <div class="m-other-0-4"></div>
        <div class="m-more-3-4"></div>
        ```
        ```css
        /* layer: other */
        .m-other-4 {
          margin: 1rem;
        }
        /* layer: stuff */
        .m-stuff-4 {
          margin: 1rem;
        }
        /* layer: more */
        .m-stuff-4 {
          margin: 1rem;
        }
        ```
        Would have to decide whether layers listed in the `layers` config get special treatment. I think probably no: simply override the config… In the above example, adding `<div class="m-stuff-4-4"></div>` would move the "stuff" layer to order 4.
4. Support dynamic `layer` values in rules' third arguments. Like the second argument, the rule regex's capture groups are available.
    🌟🌟🌟 _I like this second best_
    ```js
    export default defineConfig({
      layers: {
        stuff: 1,
        things: 2,
      },
      rules: [
        [
          /^m-([a-z]+)-(\d+)$/,
          ([,, size]) => ({
            margin: `${size / 4}rem`,
          }),
          ([, layer]) => ({
            layer: layer,
          }),
        ],
        // third argument would still accept the current shape
        [
          /^test$/,
          {
            margin: '1rem',
          },
          {
            layer: 'things',
          },
        ],
      ],
      // optional: add `outputToCssLayers: true,`
    })
    ```
    ```html
    <div class="m-stuff-4"></div>
    ```
    ```css
    /* layer: stuff */
    .m-stuff-4 {
      margin: 1rem;
    }
    ```
    Benefits
    - only one handle for controlling layer, in the rule's third argument
    - can use `symbols.parent` for other things
    - can choose to use `outputToCssLayers` or not
    - potential for teaching symbols.layers about order
        🌟🌟🌟🌟 _I like this best_
        ```js
        export default defineConfig({
          layers: {
            stuff: 1,
            things: 2,
          },
          rules: [
            [
              /^m-([a-z]+)(-\d+)?-(\d+)$/,
              ([,,, size]) => ({
                margin: `${size / 4}rem`,
              }),
              ([, layer, order]) => ({
                layer: [layer, order], // would also accept `layer: [layer]`. maybe also accept `layer: layer`? or maybe use an object instead?
              })
            ],
            // third argument would still accept the current shape
            [
              /^test$/,
             {
                margin: '1rem',
              },
              {
                layer: 'things',
              },
            ],
          ],
          // optional: add `outputToCssLayers: true,`
        })
        ```
        ```html
        <div class="m-stuff-4"></div>
        <div class="m-other-0-4"></div>
        <div class="m-more-3-4"></div>
        ```
        ```css
        /* layer: other */
        .m-other-4 {
          margin: 1rem;
        }
        /* layer: stuff */
        .m-stuff-4 {
          margin: 1rem;
        }
        /* layer: more */
        .m-stuff-4 {
          margin: 1rem;
        }
        ```
        Again, would have to decide whether layers listed in the `layers` config get special treatment. I think probably no: simply override the config… in the above example, adding `<div class="m-stuff-4-4"></div>` would move the "stuff" layer to order 4.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
