### ISSUE TITLE
CSS generated by @unocss/cli has missing font weights

### ISSUE THREAD

**Issue by fenprace** [unocss/unocss#4236]
### UnoCSS version

0.63.6

### Describe the bug

With following `uno.config.ts`, running `pnpm unocss` command is supposed to create `@font-face` rules for both Raleway and Roboto Flex in weight 400 and 600.
However, only Raleway has both 400 and 600 weight `@font-face`, 600 weight Roboto Flex `@font-face` rules are missing from generated `dist/index.css`:

```ts
import { defineConfig, presetUno, presetWebFonts } from "unocss";

export default defineConfig({
  cli: {
    entry: {
      patterns: ["src/**/*"],
      outFile: "dist/index.css",
    },
  },
  presets: [
    presetUno(),
    presetWebFonts({
      provider: "google",
      fonts: {
        sans: [
          {
            name: "Raleway",
            weights: ["400", "600"],
          },
          {
            name: "Roboto Flex",
            weights: ["400", "600"],
          },
        ],
      },
    }),
  ],
});
```

Generated `dist/index.css`:
```css
/* layer: preflights */
/* ... */
/* cyrillic-ext */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* cyrillic */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* vietnamese */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* latin-ext */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* latin */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* cyrillic-ext */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 600;
  /* ... */
}
/* cyrillic */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 600;
  /* ... */
}
/* vietnamese */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 600;
  /* ... */
}
/* latin-ext */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 600;
  /* ... */
}
/* latin */
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 600;
  /* ... */
}
/* cyrillic-ext */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* cyrillic */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* greek */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* vietnamese */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* latin-ext */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* latin */
@font-face {
  font-family: 'Roboto Flex';
  font-style: normal;
  font-weight: 400;
  /* ... */
}
/* missing Roboto Flex font-weight: 600 rules! */
/* layer: default */
/* ... */
```

### Reproduction

Check https://github.com/fenprace/preset-web-fonts-reproduction .
To reproduce, clone the repository, run `pnpm i` & `pnpm unocss`, and check `dist/index.css`.

*Notably, I was able to reproduce this bug solidly with my local environment and this [codesandbox instance](https://codesandbox.io/p/github/fenprace/preset-web-fonts-reproduction/main). But I was not able to reproduce this with StackBlitz environment.*

### System Info

macOS 15.1
node v18.17.1
pnpm 9.12.3
vite 5.4.10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
