### ISSUE TITLE
CSS inside `@screen` directives not transformed by Astro

### ISSUE THREAD

**Issue by sproott** [unocss/unocss#4344]
### UnoCSS version

0.65.2

### Describe the bug

When using the `@screen` directive in Astro, the CSS inside its body is not being transformed by Astro to be scoped to the component. E.g. the following code:

```css
@screen sm {
  div > h1 {
    color: red;
  }
}
```

Transforms to:

```css
@media (min-width: 640px) {
  div>h1 {
    color:red
  }
}
```

In an Astro component, it should instead transform to something like this:

```css
@media (min-width: 640px) {
  div[data-astro-cid-j7pv25f6]>h1[data-astro-cid-j7pv25f6] {
    color:red
  }
}
```

### Reproduction

[Repository](https://github.com/sproott/unocss-directives-astro)

[Deployment](https://unocss-directives-astro.vercel.app/)

The first heading is the broken one, the one second works as expected as it's using `@media` directly, instead of the directive.

### System Info

Using Astro version 5.1.0.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
