### ISSUE TITLE
preset-wind4 seems to refer to the colors incorrectly

### ISSUE THREAD

**Issue by csabaxyz** [unocss/unocss#4460]
### UnoCSS version

66.1.0-beta.2

### Describe the bug

When trying out `preset-wind4` I noticed that the colors are not referenced correctly. The theme layer uses plural in the variable names, while the generated classes use singular.

For example:
```css
/* layer: theme */
:root {
  --colors-white: #fff;
  --colors-slate-50: oklch(0.984 0.003 247.858);
}

.bg-white{
  --un-bg-opacity: 100%;
  background-color: color-mix(in oklch, var(--color-white) var(--un-bg-opacity), transparent);
}
```

Probably coming from here:
https://github.com/unocss/unocss/blob/ad5b40b7bbaac9c128cc6ace157de71dd4e83b3f/packages-presets/preset-wind4/src/utils/utilities.ts#L144

But the color variables should probably use singular to follow Tailwind's naming convention.

### Reproduction

https://unocss.dev/play/#version=66.1.0-beta.2&html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtAdwAswAXAUynIA8TcIwB7OM2gFgAZ2oAHXV9AHwAJMnDgNgAenAQBQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQokscYUVK1QwA6tmQAWClRq0AAoxbsA9AKEiAtAHcJkrp1QAPXvDToAhvQA2ZjNjwFiACgSc4-QcJisAXHABtdw9PDTE9ZwBKYIBdTlJooA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
