### ISSUE TITLE
PresetWind4 and transformerDirectives conflict issues

### ISSUE THREAD

**Issue by wuiyang** [unocss/unocss#4568]
### UnoCSS version

66.1.0-beta.9

### Describe the bug

When using `presetWind4` and transformers `transformerDirectives`, using some classes (such as `ease`) would produce `TypeError: x.children is undefined` in browser playground, and `Pre-transform error: Cannot read properties of undefined (reading 'forEach')` in node environment.

This issue occurs from 66.1.0-beta.9 and 66.1.0-beta.10, but has no issue in 66.1.0-beta.8.

The error occurs in this line of code.
https://github.com/unocss/unocss/blob/a7ec2e4aee969a87e074828a183d14fa232951f9/packages-presets/transformer-directives/src/apply.ts#L99-L101

In v66.1.0-beta.9, VSCode UnoCSS intellisense shows the CSS code below for `ease-out`. Showing

```css
/* layer: default */
.ease-out {
  --un-ease: var(--ease-out);
  transition-timing-function: var(--ease-out);
}
.ease-out {
  syntax: "*";
  inherits: false;
}
```

![Image](https://github.com/user-attachments/assets/d2cddf25-72c4-4aa6-b2db-1477e86bc2a1)

In v66.1.0-beta.8, VSCode UnoCSS intellisense shows the CSS code below for `ease-out`.

```css
/* layer: default */
.ease-out {
  --un-ease: var(--ease-out);
  transition-timing-function: var(--ease-out);
}
@property --un-ease {
  syntax: "*";
  inherits: false;
}
```

![Image](https://github.com/user-attachments/assets/730da80e-de44-46c1-ad11-86b00d19a5ec)

### Reproduction

https://unocss.dev/play/#version=66.1.0-beta.9&html=DwEwlgbgBAxgNgQwM5ILwCJ0D4BQUoD2AdgLQgCmAtgkSFAO1RhFIAuNrDUAZgK5xwAnrF5sClMAC8EAIzjkcwAPTgIWIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAHU8aACyy2AQ1x0s0EBigARYLQm8AbvQ1Rtu-YYBqm9tpgBxKBC5hKAXzgsLxA4AHIuXAgJOjpQpFBIWEQ4CxdgNwBZTRgJAAtDOACgiBCAIgABCKiYgHooLgAbDABaHmAGulKAbiQkDAAPRPhMLE1G4ew8QmIyAApkYXlGOgAuOABtKkXRJRVVWYBKWQBdGzs9KAMoVY2tHQurkzNLekPTpD8DpCA&css=HQMwhgJgpgtANlMA3WYDGAXAligBAbwChdcABMABwrgE9dEBnKAbkIF9Cg&options=N4XyA

### System Info

Firefox 137
Node v20.16.0
NPM 10.8.1
Windows 11
Nuxt 3

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
