### ISSUE TITLE
preset-wind4 colors declaration opacity is incorrect

### ISSUE THREAD

**Issue by rozsazoltan** [unocss/unocss#4579]
### UnoCSS version

66.1.0-beta.10 (`@unocss/preset-wind4`)

### Describe the bug

If I declare a color in wind4, the corresponding class is created, but it contains an invalid setting, which is why the color doesn't appear.

### Reproduction

**uno.config.ts**
```ts
import presetWind4 from '@unocss/preset-wind4';
import { defineConfig } from 'unocss';

export default defineConfig({
  presets: [presetWind4()],
  theme: {
    colors: {
      veryCool: '#0ff', // here
    },
  },
});
```

* https://stackblitz.com/edit/vitejs-vite-tjji3wus?file=uno.config.ts

Please excuse me, it's not a professional reproduction, I just found an existing one on the internet, added the wind4, and it's visible that the div placed in the index.html doesn't display the correct color. However, when checking the developer tools, it's clear that the class was created:

```css
:root, :host {
  --colors-very-cool: #0ff;
}

.text-very-cool {
  color: color-mix(in oklch, var(--colors-very-cool) var(--un-text-opacity), transparent);
}
```

But this way, the basic syntax of CSS doesn't allow the code to run; the reason for this is:

> `--un-text-opacity` is not defined

The perfect solution would be a fallback 100% value:

```css
:root, :host {
  --colors-very-cool: #0ff;
}

.text-very-cool {
  color: color-mix(in oklch, var(--colors-very-cool) var(--un-text-opacity, 100%), transparent);
}
```

I found the error on Stack Overflow and answered it there. You can also quickly check the executable code snippets there:
* [Add custom theme spacing to unocss for tailwind 4 preset](https://stackoverflow.com/a/79561728/15167500)

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
