### ISSUE TITLE
preset-wind4 cannot add prefix to CSS variables like `--colors-blue-500`

### ISSUE THREAD

**Issue by ocavue** [unocss/unocss#4620]
### UnoCSS version

66.1.0-beta.12

### Describe the bug

To avoid CSS conflicts, I'd like to add a prefix to all CSS class names (like `bg-blue-500` -> `unoprefix-bg-blue-500`) and variables (like `--colors-blue-500` -> `--unoprefix-colors-blue-500`), but it seems that `presetWind4` cannot rename variable names introduced in TailwindCSS v4.

### Reproduction

Reproduction: https://github.com/issueset/test-uno-tail-4

Expected output ([dist/output_tailwind/output.css](https://github.com/issueset/test-uno-tail-4/blob/41bcc299e5bc3c5aa619de25c6cbdc4ea91ad7c6/dist/output_tailwind/output.css#L6)):

```css
/* ... */
--tailwindprefix-color-red-500: oklch(63.7% 0.237 25.331);
/* ... */
.tailwindprefix\:bg-red-500\/50 {
    background-color: var(--tailwindprefix-color-red-500);
    /* ... */
}
/* ... */
```

Actual output ([dist/output_unocss/output.css](https://github.com/issueset/test-uno-tail-4/blob/41bcc299e5bc3c5aa619de25c6cbdc4ea91ad7c6/dist/output_unocss/output.css)):

```css

@property --un-bg-opacity {
  /* ... */
}
/* ... */
  --colors-blue-500: oklch(0.623 0.214 259.815);
/* ... */
.unoprefix-bg-blue-500\/50 {
  --unovariableprefix-bg-opacity: 50%;
  background-color: color-mix(
      in oklch,
      var(--colors-blue-500) var(--unovariableprefix-bg-opacity),
      transparent
    )
    /* oklch(0.623 0.214 259.815) */;
}
```

There are in fact two issues in the UnoCSS's output:

1. `--colors-blue-500` has no prefix
2. `@property --un-bg-opacity` and `--unovariableprefix-bg-opacity` use different names.

### System Info

N/A

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
