### ISSUE TITLE
Curly braces in comments lead to wrong output

### ISSUE THREAD

**Issue by OverflowCat** [unocss/unocss#4639]
### UnoCSS version

v66.1.0

### Describe the bug

```css
.aaa {
  @apply text-blue-500;
  font-size: 1.5em;
  /* {} ← empty curly brace in comment will lead to wrong parsing */
  font-weight: 900;
}
```

generates

```css
/* layer: playground */
.aaa {← empty curly brace in comment will lead to wrong parsing */
font-weight: 900;
}
```

https://github.com/user-attachments/assets/c0b30efd-b96f-4c72-8bb5-d3ad4aad91cc

### Reproduction

[https://unocss.dev/play/~](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIFfQPgC4AWYSUSBA9gK5whQBGAplIgE4DmTCAdrXXJQ2AB6cBBwAoYAAccdSnijkuMJoQYtOGqEIDeAHSQBqPQF8hUMFygBhAMq3xMcgFtnDLniQAaKGtjkQJkYAM3ItPydXdwUELWdiJEs2ADpJIRkgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAsnsJQL5xZQQhwDkAV1wQAxnTr8koSLDgwoAQ1x0s0EBigARYLVExgAN3pceffgAFhYiQHoFy1es0BaNLoz6j9KUgwAPWXhMLEVBABtg7DxCYjIACmRUGnpGOgAuOABtFIZmVniASgBdSlQHFTUoDSgM7Iqnas0dPQNjOiLipHZCpCA&css=HQQzAIG8Ch3ABEAHJAbAnuALgUwB5YC0ARqgK46ECsADDQNyzgBmA9gHZEDOAlgF44AXOACMwKjgC2jOAHoAVFAC%2B4ebKZtOhAO44eAcwAWWYQE46jJdCA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA&version=66.1.0)

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
