### ISSUE TITLE
Unintended class generated

### ISSUE THREAD

**Issue by sep2** [unocss/unocss#4658]
### UnoCSS version

66.1.1

### Describe the bug

<img width="1022" alt="Image" src="https://github.com/user-attachments/assets/604afa51-4a16-4119-98e9-a093829d9eef" />

The question mark along should not generate the class `.\?`

### Reproduction

This file

```tsx
export function Test() {
    return <div>{true ? 1 : 0}</div>
}
```

generates
```css
/* layer: default */
@keyframes __un_qm {
  0% {
    box-shadow: inset 4px 4px #ff1e90, inset -4px -4px #ff1e90;
  }
  100% {
    box-shadow: inset 8px 8px #3399ff, inset -8px -8px #3399ff;
  }
}
.\? {
  animation: __un_qm 0.5s ease-in-out alternate infinite;
}
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
