### ISSUE TITLE
presetWind4() font-variant-numeric invalid due to undefined variables

### ISSUE THREAD

**Issue by 5P5** [unocss/unocss#4745]
### UnoCSS version

66.2.1

### Describe the bug

very broken.
generates a `.proportional-nums, .tabular-nums{syntax:"*";inherits:false;}` rule??

in the rule 
```css
.tabular-nums {
    --un-numeric-spacing: tabular-nums;
    font-variant-numeric: var(--un-ordinal) var(--un-slashed-zero) var(--un-numeric-figure) var(--un-numeric-spacing) var(--un-numeric-fraction);
}
```
the variables `var(--un-ordinal) var(--un-slashed-zero) var(--un-numeric-figure) var(--un-numeric-fraction)` are all undefined, making the rule invalid and not rendering proper numeric font variant.

same goes for `proportional-nums`.

relevant?
https://github.com/unocss/unocss/pull/429
https://github.com/unocss/unocss/pull/199
https://github.com/unocss/unocss/issues/195

### Reproduction

[play](https://unocss.dev/play/#html=DwBwBAxgNghgznAvAIgC4wEYFdYCcC0AdlgLZzIB8ADAIx0BMArAJwAcA7MAPQgUBQoSLAQoQuAPYhxuVAEtxhGFCKly1OjSZtOPfoLioAnlACmKAGYLU%2BAG4xcsmIWvESJhxABc6bHhVlKWgYWDm5eIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owDq2yALHAL5zpQQhwDkArlggBjKlV4AoVAA9IsFBgCG-ADbw0mHPkLAiACiQVqtKgC44AbSM16jJnoCUAXTYOgA&css=Q&options=N4XyA&version=66.2.1)

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
