### ISSUE TITLE
[transformer-directives] support default value for `theme()` function

### ISSUE THREAD

**Issue by lyonbot** [unocss/unocss#4785]
### Clear and concise description of the problem

In taliwind preflight.css, `theme()` accepts 2nd optional parameter as default value:

```css
code,
kbd,
samp,
pre {
  font-family: theme('fontFamily.mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace); /* 1 */
  font-feature-settings: theme('fontFamily.mono[1].fontFeatureSettings', normal); /* 2 */
  font-variation-settings: theme('fontFamily.mono[1].fontVariationSettings', normal); /* 3 */
  font-size: 1em; /* 4 */
}
```

but for now UnoCSS only accept one parameter. is it okay to support the default value?

https://github.com/unocss/unocss/blob/0a8d10d7799540650e5575c339aafcc36ef0f36b/packages-presets/transformer-directives/src/functions.ts#L6-L23

### Suggested solution

`theme()` support 2nd parameter as default value.

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/.github/CONTRIBUTING.md).
- [x] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
