### ISSUE TITLE
Bad order :hover, :active

### ISSUE THREAD

**Issue by idmytro** [unocss/unocss#583]
Same as in windi now
https://github.com/windicss/windicss/issues/687

I try `<button class="hover:bg-yellow-300 active:bg-blue-300">Button</button>` in unocss playground
and I got
```css
.active\:bg-blue-300:active{--un-bg-opacity:1;background-color:rgba(147,197,253,var(--un-bg-opacity));}
.hover\:bg-yellow-300:hover{--un-bg-opacity:1;background-color:rgba(253,224,71,var(--un-bg-opacity));}
```
So I never see my active styles, and I need to use !important
But tailwind order is more natural: `:hover` first, `:active` second
