### ISSUE TITLE
Problem with variant group (vite + vue-ts)

### ISSUE THREAD

**Issue by joezak11** [unocss/unocss#673]
```vue
<!-- App.vue -->

<style>
  #app {
    @apply ... @dark:(bg-[#000000] text-[#ffffff]);
  }
</style>
```
building results in
```css
@media (prefers-color-scheme: dark) {
  #app {
    --un-bg-opacity: 1;
    background-color: rgba(0, 0, 0, var(--un-bg-opacity));
  }
}
.dark #app {
  --un-text-opacity: 1;
  color: rgba(255, 255, 255, var(--un-text-opacity));
}
```
expected result
```css
@media (prefers-color-scheme: dark) {
  #app {
    --un-bg-opacity: 1;
    background-color: rgba(0, 0, 0, var(--un-bg-opacity));
    --un-text-opacity: 1;
    color: rgba(255, 255, 255, var(--un-text-opacity));
  }
}
```
