### ISSUE TITLE
Optimize CSS directives

### ISSUE THREAD

**Issue by joezak11** [unocss/unocss#674]
```vue
<!-- App.vue -->

<style>
  #app {
    @apply ... dark:(bg-[#000000] text-[#ffffff]);
  }
</style>
```
building results in
```css
.dark #app {
  --un-bg-opacity: 1;
  background-color: rgba(0, 0, 0, var(--un-bg-opacity));
  --un-text-opacity: 1;
  color: rgba(255, 255, 255, var(--un-text-opacity));
}
/* the following classes are unnecessary since they are never used */
.dark .dark\:bg-\[\#000000\] {
  --un-bg-opacity: 1;
  background-color: rgba(0, 0, 0, var(--un-bg-opacity));
}
.dark .dark\:text-\[\#ffffff\] {
  --un-text-opacity: 1;
  color: rgba(255, 255, 255, var(--un-text-opacity));
}
```
`bg-[#000000]` and `text-[#ffffff]` are only used inside `@apply`
