### ISSUE TITLE
Uno preset (also in preset-wind) - broken css style for grid

### ISSUE THREAD

**Issue by Kylyi** [unocss/unocss#675]
```html
<div class="grid grid-rows-[auto,1fr]">
    ...
</div>
```

generates broken css:

```css
.grid-rows-\[auto\,1fr\] {
  grid-template-rows: auto,1fr; <-- notice the `,` instead of ` `
}
```

Note: also happens for `grid-cols`
