### ISSUE TITLE
bug(transformer-directives): not handling sm:hover:*

### ISSUE THREAD

**Issue by privatenumber** [unocss/unocss#678]
## Bug description

When combining `sm` with `hover`, the `hover` is ignored:
### Input
```css
.some-class {
	@apply sm:hover:bg-black;
}
```

### Output
```css
.some-class {
}

@media (min-width: 640px) {
  .some-class {
    --un-bg-opacity: 1;
    background-color: rgba(0, 0, 0, var(--un-bg-opacity));
  }
}
```

However, when putting `sm:hover:bg-black` in a class, it works fine.

## Expected
For the output to only apply `bg-black` on `hover` given the screen is `sm`.

## Reproduction

https://github.com/privatenumber/issue-reproductions/tree/master/reproductions/unocss/unocss/1

<details>
<summary>Code</summary>

```js
import { createGenerator, presetUno } from 'unocss';
import { transformDirectives } from '@unocss/transformer-directives';
import MagicString from 'magic-string-extra';
import prettier from 'prettier/standalone.js';
import parserCSS from 'prettier/parser-postcss.js';

const uno = createGenerator({
	presets: [
		presetUno(),
	],
});

async function transform(code) {
	const s = new MagicString(code);
	await transformDirectives(s, uno);
	return prettier.format(s.toString(), {
		parser: 'css',
		plugins: [parserCSS],
	});
}

const output = await transform(`
.some-class {
	@apply sm:hover:bg-black;
}
`);

console.log('output', output);

```

</details>
