### ISSUE TITLE
Add support for @screen directive and custom media queries

### ISSUE THREAD

**Issue by Hebilicious** [unocss/unocss#715]
Would love to see the "@screen" directive being implemented :

- [Windi reference](https://windicss.org/features/directives.html#screen)
- [Tailwind reference](https://tailwindcss.com/docs/screens#custom-media-queries) 

In my opinion, the most useful feature would be the ability to use custom media queries with `@screen` like this
(currently this works with tailwind/windi)

```ts
//unocss.config.ts
export default defineConfig({
    theme: {
        extend: {
            screens: {
                mobile: {
                    raw: "screen and (min-width: 320px) and (max-width: 900px)"
                }
            }
        }
    }
})
  ```
  Then this can be used in styles like this :

  ```css
  @screen mobile {
      color: red;
  }
  ```

  and it gets transformed into the following css :
  
```css
  @media screen and (min-width: 320px) and (max-width: 900px) {
      color: red;
  }
 ```
