### ISSUE TITLE
Colors with opacity are not escaped in shadow-dom mode 

### ISSUE THREAD

**Issue by MarvinRudolph** [unocss/unocss#739]
Hey! While testing with the shadow-dom mode and defining custom colors I stumbled upon the issue that the generated colors inside the `<style>` are not escaped. All colors defined with the opacity e.g. `text-red-500/30` are rendered 1:1 and not as `text-red-500\/30`. Manually adding the \ to the generated styles works. 

Generated styles:
```css
/* layer: default */
.bg-blue-500/50{background-color:rgba(59,130,246,0.5);}
.p-5{padding:1.25rem;}
.text-2xl{font-size:1.5rem;line-height:2rem;}
.text-indigo-500{--un-text-opacity:1;color:rgba(99,102,241,var(--un-text-opacity));}
.text-primary/50{color:rgba(var(--color-primary),0.5);}
```

Reproduction:
https://stackblitz.com/edit/vitejs-vite-v5dbag?file=main.tsx
