### ISSUE TITLE
matcher or rule ?

### ISSUE THREAD

**Issue by transtone** [unocss/unocss#765]
I want add a matcher start with `'i_'` like this:

```html
<div class="i_font-12px" />
```
want it to
```css
i_font-12px {
    font-size: 12px !important;
}
```

how can I write the config, use matcher or rule?
