### ISSUE TITLE
@apply doesn't work with custom advanced rules (ones that return a CSS string)

### ISSUE THREAD

**Issue by froggydood** [unocss/unocss#823]
When using a custom advanced rule (one that returns a css string) the css string gets passed in the body of the selector instead of separately:

```javascript
Unocss({
  rules: [
    [/^flex-gap-x-(\d+)$/, ([_, gapSize], { rawSelector, currentSelector, variantHandlers, theme }) => {
    return `
      .${escapeSelector(currentSelector)} > *:not(:last-child) {
       margin-right: ${Number.parseFloat(gapSize) / 4}rem;
      }
    `
    }],
  ]
})
```

The CSS I've written:

```css
.test {
 @apply flex-gap-x-4
}
```
The CSS generated is:

```css
.test {
  .flex-gap-x-4 > *:not(:last-child) {
    margin-right: 1rem;
  }
}
```

Which is invalid CSS.

The rule applies just fine if you just apply the `flex-gap-x-4` class directly, but not inside of the `@apply`

The CSS that should be generated is:

```css
.test > *:not(:last-child) {
    margin-right: 1rem;
}
```
