### ISSUE TITLE
Is there a way to merge custom MediaQuery rules

### ISSUE THREAD

**Issue by sohaha** [unocss/unocss#832]
expected:

```css
hh-3 {
  height: 13px;
}
ww-6 {
  width: 16px;
}
@media (min-width: 640px) {
  ww-6 {
    width: 6px;
  }
  hh-3 {
    height: 3px;
  }
}
```

play: https://unocss.antfu.me/?html=FAHgJglgbgBAxgGwIYGcUF4BEALbBaAZhgHdi8A2TAPmBhgBcBTFe0AekiiqA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANDBAKIDOAxgIZirIDKqANqjeVAL5zpQIIOAHIArlgg0qVEQCg5qAB6RYKDHTFt4aTDnyFgRABQI5cOFC2oqALjgBtcxYsOA9AD0AFl4C0xgB1kAGoASgASNxI4YwdorDoQVABdaKQoOgB3Vg4uaDgeULgAXgA%2BRGcXOBoCKngqdk5uEsssnKboSpcoVBgxKCw4AAMui3CEBtzuPgQvVCMvGHtxgEYABjhgmOCEpNCeMCUAbh5RuAABJORgOhiQbF9M4GQYL3sANgAWNcOisyqquNJh1eIg5gslnBxrtUAdjqcAQU5CMqjxUqN3B5Mpl-EEwpForF4okUmlWtlGnkoAUimUKoialg6nBgVSWhkKVNOoien0BsMzkDKdNEE8Xm8oQh1pttjD9ocTmdLkwbncHmLXh9vr96YjJayRQgNRLoSS4YrEacUS40SRnMk5IUgA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2TXQF8g
