### ISSUE TITLE
希望支持 inset 特性

### ISSUE THREAD

**Issue by elkon028** [unocss/unocss#877]
## inset
```scss
# class="p[1px, 2rem, 3, 0] abs[1px, 2rem, 3, 0]"
.out{
  padding: 1px 2rem 3rem 0;
  position: absolute;
  inset: 1px 2rem 3 0;
}

# class="p[1, 2]"
# <div p="[1, 2]" />
.out{
  padding: 1rem 2rem;
}
```
## hover
```scss
# class="color[red, green] bg[gray, blue]"
# <div color="[red, green]" bg="[gray, blue]" />
.out{
  color: red;
  background: gray;
  &:hover{
    color: green;
    background: blue;
  }
}
```

## font
```scss
# class="font[style, name, size, color]"
# class="font[bold, input mono, 12px, red]"
.out{
  font-style: bold,
  font-family: input mono;
  font-size: 12px;
  color: red;
}
```
## Other similar
......
