### ISSUE TITLE
Changing sans font in theme does not change html font-family

### ISSUE THREAD

**Issue by char101** [unocss/unocss#924]
unocss config:

```js
  Unocss({
      theme: {
        fontFamily: {
          sans: ['Droid Sans'],
          mono: ['JetBrains Mono'],
        },
      },
      presets: [presetUno()],
      extractors: [extractorSplit, extractorPug()],
      transformers: [transformerDirective({enforce: 'pre'})],
    }),
  ],
```

Applied styles:

```js
import '@unocss/reset/tailwind.css';
import 'uno.css';
```

`html` element still uses the default sans font configuration. Only elements explicitly styled with `font-sans` will use the new sans font family.

```css
html {
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
  -moz-tab-size: 4;
  tab-size: 4;
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```

**Comment by zirbest** [comment]
`reset/tailwind.css`
add this
```css
html {
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
  -moz-tab-size: 4;
  tab-size: 4;
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```

use
```html
<body class="font-sans"> 
```
