### ISSUE TITLE
With nuxt, if using a standalone configuration `uno.config.ts`, the class `space-{direction}-{number}` is incorrectly generated

### ISSUE THREAD

**Issue by leo91000** [unocss/unocss#989]
I have a weird issue with unocss & nuxt & css class `space-{direction}-{number}`. The class is not applied and the generated css seems wrong :

```css
.space-y-3 > :not([hidden]) ~ :not([hidden]) > :not([hidden]) ~ :not([hidden]) {
    --un-space-y-reverse: 0;
    margin-bottom: calc(.75rem * var(--un-space-y-reverse));
    margin-top: calc(.75rem * (1 - var(--un-space-y-reverse)))
}
```

The var `--un-space-y-reverse` is set to 0 where it should be 3

Here a very simple stackblitz repro : https://stackblitz.com/edit/github-xishze-ftqdny?file=app.vue,uno.config.ts
